# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=220)),
                ('summary', models.TextField()),
                ('body_markdown', models.TextField()),
                ('provenance_kind', models.CharField(default='generated', max_length=20)),
                ('input_manifest_hash', models.CharField(max_length=64)),
                ('claim_manifest_hash', models.CharField(max_length=64)),
                ('quality_manifest_hash', models.CharField(max_length=64)),
                ('quality_state', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('fact', '사실'), ('interpretation', '해석'), ('outlook', '전망'), ('company_claim', '기업 주장')], max_length=24)),
                ('text', models.TextField()),
                ('position', models.PositiveIntegerField()),
                ('citation_marker', models.CharField(max_length=30)),
                ('high_impact', models.BooleanField(default=False)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='editorial.articlerevision')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DraftArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article_identity_key', models.CharField(max_length=200, unique=True)),
                ('topic_code', models.CharField(db_index=True, max_length=40)),
                ('article_type', models.CharField(max_length=40)),
                ('state', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='editorial.articlerevision')),
                ('source_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='collection.collectionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='editorial.draftarticle'),
        ),
        migrations.CreateModel(
            name='EventCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_code', models.CharField(max_length=40)),
                ('canonical_key', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('verification_state', models.CharField(default='candidate', max_length=40)),
                ('source_item_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('topic_code', 'canonical_key'), name='uq_event_cluster_key')],
            },
        ),
        migrations.CreateModel(
            name='GenerationAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generator_name', models.CharField(default='source_grounded_template', max_length=100)),
                ('generator_version', models.CharField(default='v1', max_length=40)),
                ('input_manifest_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='running', max_length=20)),
                ('error_detail_redacted', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_attempts', to='editorial.draftarticle')),
            ],
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='generation_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='editorial.generationattempt'),
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='editorial.articlerevision')),
            ],
        ),
        migrations.CreateModel(
            name='VisualizationRender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('transform_spec', models.JSONField(default=dict)),
                ('input_manifest_hash', models.CharField(max_length=64)),
                ('object_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('alt_text', models.CharField(max_length=500)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='editorial.articlerevision')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_kind', models.CharField(default='supports', max_length=20)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='editorial.claim')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='evidence.evidenceasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'evidence'), name='uq_claim_evidence')],
            },
        ),
        migrations.CreateModel(
            name='CorrectionCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='correction', max_length=32)),
                ('state', models.CharField(choices=[('detected', '감지'), ('verifying', '검증'), ('verified', '확인'), ('applying', '반영'), ('completed', '완료'), ('rejected', '거절'), ('failed', '실패')], default='detected', max_length=20)),
                ('subject_hash', models.CharField(max_length=64)),
                ('diff_summary', models.JSONField(default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prior_source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_corrections', to='collection.sourceitem')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.sourceitem')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_cases', to='editorial.draftarticle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'subject_hash'), name='uq_article_correction_subject')],
            },
        ),
        migrations.AddConstraint(
            model_name='articlerevision',
            constraint=models.UniqueConstraint(fields=('article', 'revision_no'), name='uq_article_revision_no'),
        ),
        migrations.AddConstraint(
            model_name='qualitycheck',
            constraint=models.UniqueConstraint(fields=('revision', 'code'), name='uq_revision_quality_code'),
        ),
    ]
