# Generated by Django 5.2.16 on 2026-08-09 00:26

import hashlib
import uuid

import django.core.validators
import django.db.models.deletion
import rfc8785
from django.db import migrations, models
from django.utils import timezone


REQUIRED_GATES = (
    'all_publishable_claims_grounded',
    'high_risk_verification_satisfied',
    'claim_independence_satisfied',
    'source_freshness_satisfied',
    'evidence_publish_eligibility_current',
    'quotation_limits_satisfied',
    'claim_types_separated_and_attributed',
    'duplicate_or_conflict_resolved',
    'korean_readability_and_repetition',
    'no_exaggeration_or_false_experience',
)


def _hash(value):
    return hashlib.sha256(rfc8785.dumps(value)).hexdigest()


def quarantine_legacy_editorial_rows(apps, schema_editor):
    alias = schema_editor.connection.alias
    Policy = apps.get_model('editorial', 'EditorialPolicySnapshot')
    Attempt = apps.get_model('editorial', 'GenerationAttempt')
    Revision = apps.get_model('editorial', 'ArticleRevision')
    Claim = apps.get_model('editorial', 'Claim')
    ClaimEvidence = apps.get_model('editorial', 'ClaimEvidence')
    QualityCheck = apps.get_model('editorial', 'QualityCheck')
    Article = apps.get_model('editorial', 'DraftArticle')
    Run = apps.get_model('collection', 'CollectionRun')
    RunStep = apps.get_model('collection', 'RunStep')

    sentinel = {
        'schemaVersion': 'editorial-policy-legacy-quarantine-v1',
        'policyKey': 'legacy-unverified',
        'topicCode': 'legacy',
        'policyVersion': '0',
        'runtimeEligible': False,
    }
    config_hash = _hash(sentinel)
    release_document_hash = _hash({'legacyRelease': sentinel})
    implementation_manifest = {
        'schemaVersion': 'editorial-implementation-manifest-v1',
        'files': [],
        'legacyQuarantine': True,
    }
    implementation_manifest_hash = _hash(implementation_manifest)
    sentinel_hash = _hash({
        'schemaVersion': 'editorial-policy-release-material-v1',
        'releaseDocumentHash': release_document_hash,
        'configHash': config_hash,
        'implementationManifestHash': implementation_manifest_hash,
    })
    policy = Policy.objects.using(alias).create(
        topic_code='legacy',
        policy_key='legacy-unverified',
        policy_version='0',
        document=sentinel,
        release_document_hash=release_document_hash,
        config_hash=config_hash,
        implementation_manifest=implementation_manifest,
        implementation_manifest_hash=implementation_manifest_hash,
        material_hash=sentinel_hash,
    )
    empty_hash = _hash([])
    pending_hash = _hash({'state': 'legacy_quarantine'})
    for attempt in Attempt.objects.using(alias).select_related('article'):
        attempt.origin_run_id = attempt.article.source_run_id
        attempt.editorial_policy_snapshot_id = policy.id
        attempt.editorial_policy_version = '0'
        attempt.editorial_policy_hash = sentinel_hash
        attempt.verification_manifest = []
        attempt.verification_manifest_hash = empty_hash
        attempt.evidence_manifest = []
        attempt.evidence_manifest_hash = empty_hash
        attempt.exclusion_manifest = []
        attempt.exclusion_manifest_hash = empty_hash
        attempt.visual_manifest = []
        attempt.visual_manifest_hash = empty_hash
        attempt.generation_pipeline_manifest_hash = pending_hash
        attempt.save(using=alias, update_fields=(
            'origin_run', 'editorial_policy_snapshot',
            'editorial_policy_version', 'editorial_policy_hash',
            'verification_manifest', 'verification_manifest_hash',
            'evidence_manifest', 'evidence_manifest_hash',
            'exclusion_manifest', 'exclusion_manifest_hash',
            'visual_manifest', 'visual_manifest_hash',
            'generation_pipeline_manifest_hash',
        ))
    terminal_article_states = {
        'published', 'publishing', 'correction_pending', 'stopped', 'failed'
    }
    for revision in Revision.objects.using(alias).select_related(
        'article', 'article__source_verification'
    ):
        verification = revision.article.source_verification
        if verification is None:
            verification_manifest = []
        else:
            verification_manifest = [{
                'verificationId': str(verification.id),
                'clusterId': str(verification.cluster_id),
                'role': 'lead',
                'version': verification.version,
                'decision': verification.decision,
                'articleType': verification.article_type,
                'category': verification.category,
                'localEventDate': verification.local_event_date.isoformat(),
                'evidenceManifestHash': verification.evidence_manifest_hash,
                'ruleManifestHash': verification.rule_manifest_hash,
                'resultManifestHash': verification.result_manifest_hash,
                'policyVersion': verification.policy_version,
                'policyHash': verification.policy_hash,
            }]
        evidence_ids = sorted(
            str(value)
            for value in ClaimEvidence.objects.using(alias)
            .filter(claim__revision_id=revision.id)
            .values_list('evidence_id', flat=True)
            .distinct()
        )
        evidence_manifest = [
            {
                'evidenceId': evidence_id,
                'legacyQuarantine': True,
            }
            for evidence_id in evidence_ids
        ]
        exclusion_manifest = []
        if verification is not None:
            for row in verification.conflict_manifest:
                exclusion_manifest.append({
                    'selectionState': 'conflicting',
                    **row,
                })
            for row in verification.excluded_source_manifest:
                exclusion_manifest.append({
                    'selectionState': 'excluded',
                    **row,
                })
        blocks = [{
            'id': 'legacy-body',
            'type': 'background',
            'content': revision.body_markdown,
        }]
        content_hash = _hash({
            'schemaVersion': 'article-revision-content-v2',
            'title': revision.title,
            'summary': revision.summary,
            'bodyBlocks': blocks,
        })
        revision.editorial_policy_snapshot_id = policy.id
        revision.origin_run_id = (
            verification.origin_run_id
            if verification is not None
            else revision.article.source_run_id
        )
        revision.editorial_policy_version = '0'
        revision.editorial_policy_hash = sentinel_hash
        revision.event_verification_id = (
            verification.id if verification is not None else None
        )
        revision.verification_manifest = verification_manifest
        revision.verification_manifest_hash = _hash(verification_manifest)
        revision.evidence_manifest = evidence_manifest
        revision.evidence_manifest_hash = _hash(evidence_manifest)
        revision.exclusion_manifest = exclusion_manifest
        revision.exclusion_manifest_hash = _hash(exclusion_manifest)
        revision.visual_manifest = []
        revision.visual_manifest_hash = _hash([])
        revision.body_blocks = blocks
        revision.claim_bindings = []
        revision.content_hash = content_hash
        revision.claim_graph_state = 'blocked'
        revision.quality_state = 'failed'
        revision.quality_gate_manifest_hash = pending_hash
        revision.quality_report_hash = pending_hash
        revision.quality_manifest_hash = pending_hash
        revision.save(using=alias, update_fields=(
            'editorial_policy_snapshot', 'origin_run',
            'editorial_policy_version',
            'editorial_policy_hash', 'event_verification',
            'verification_manifest', 'verification_manifest_hash',
            'evidence_manifest', 'evidence_manifest_hash',
            'exclusion_manifest', 'exclusion_manifest_hash', 'body_blocks',
            'visual_manifest', 'visual_manifest_hash',
            'claim_bindings', 'content_hash', 'claim_graph_state',
            'quality_state', 'quality_gate_manifest_hash',
            'quality_report_hash', 'quality_manifest_hash',
        ))
        if revision.article.state not in terminal_article_states:
            Article.objects.using(alias).filter(pk=revision.article_id).update(
                state='blocked'
            )
        existing_codes = set(
            QualityCheck.objects.using(alias)
            .filter(revision_id=revision.id)
            .values_list('code', flat=True)
        )
        detail = {'reason': 'legacy_unproven_editorial_material'}
        for code in REQUIRED_GATES:
            if code not in existing_codes:
                QualityCheck.objects.using(alias).create(
                    revision_id=revision.id,
                    code=code,
                    check_version='legacy-quarantine-v1',
                    result='failed',
                    blocking=True,
                    details=detail,
                    details_hash=_hash(detail),
                )
    for claim in Claim.objects.using(alias).all():
        material = {
            'schemaVersion': 'editorial-claim-subject-legacy-v1',
            'claimId': str(claim.id),
            'statement': claim.text,
        }
        claim.block_id = claim.block_id or 'legacy-body'
        claim.risk_level = 'high' if claim.high_impact else 'normal'
        claim.verification_state = 'rejected'
        claim.subject_hash = _hash(material)
        claim.save(using=alias, update_fields=(
            'block_id', 'risk_level', 'verification_state', 'subject_hash'
        ))
    for link in ClaimEvidence.objects.using(alias).all():
        material = {
            'schemaVersion': 'editorial-claim-evidence-legacy-v1',
            'claimId': str(link.claim_id),
            'evidenceId': str(link.evidence_id),
            'legacyQuarantine': True,
        }
        link.source_span_hash = _hash(None)
        link.verification_strength = 'unproven'
        link.frozen_material = material
        link.frozen_material_hash = _hash(material)
        link.save(using=alias, update_fields=(
            'source_span_hash', 'verification_strength',
            'frozen_material', 'frozen_material_hash'
        ))
    for check in QualityCheck.objects.using(alias).all():
        check.blocking = True
        check.result = 'failed'
        check.details_hash = _hash(check.details)
        check.save(using=alias, update_fields=(
            'blocking', 'result', 'details_hash'
        ))

    # A legacy revision cannot prove its frozen policy/evidence material.  If
    # its origin run is still active, leaving only the article blocked would
    # strand the collection state machine.  Close the run and every active
    # step as one migration transaction so pending legacy events cannot revive
    # a quarantined revision.
    affected_run_ids = set(
        Revision.objects.using(alias)
        .exclude(origin_run_id__isnull=True)
        .values_list('origin_run_id', flat=True)
    )
    active_run_states = {
        'queued', 'collecting', 'extracting', 'validating', 'drafting',
        'awaiting_approval', 'publishing', 'stopping',
    }
    active_step_states = {'queued', 'running', 'retry'}
    now = timezone.now()
    for run in (
        Run.objects.using(alias)
        .filter(pk__in=affected_run_ids, state__in=active_run_states)
        .order_by('id')
    ):
        impact = {
            'stage': 'editorial_migration',
            'errorCode': 'legacy_editorial_material_unproven',
            'recovery': 'manual_required',
        }
        RunStep.objects.using(alias).filter(
            run_id=run.id,
            state__in=active_step_states,
        ).update(
            state='failed',
            error_code='legacy_editorial_material_unproven',
            error_detail_redacted='Legacy editorial material was quarantined.',
            finished_at=now,
            retry_at=None,
            terminal_impact=impact,
            recovery_state='manual_required',
            lease_owner='',
            lease_token=None,
        )
        run.state = 'failed'
        run.error_summary = impact
        run.completed_at = now
        run.terminal_impact = impact
        run.recovery_state = 'manual_required'
        run.next_recovery_at = None
        run.save(using=alias, update_fields=(
            'state', 'error_summary', 'completed_at', 'terminal_impact',
            'recovery_state', 'next_recovery_at',
        ))


def install_editorial_policy_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    policy_table = schema_editor.quote_name('editorial_editorialpolicysnapshot')
    revision_table = schema_editor.quote_name('editorial_articlerevision')
    attempt_table = schema_editor.quote_name('editorial_generationattempt')
    render_table = schema_editor.quote_name('editorial_visualizationrender')
    guarded_tables = [
        'editorial_claim',
        'editorial_claimevidence',
        'editorial_qualitycheck',
        'editorial_visualplacement',
    ]
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute(f'''
                CREATE TRIGGER editorial_policy_snapshot_append_only_update
                BEFORE UPDATE ON {policy_table}
                BEGIN SELECT RAISE(ABORT, 'EditorialPolicySnapshot is append-only'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_policy_snapshot_append_only_delete
                BEFORE DELETE ON {policy_table}
                BEGIN SELECT RAISE(ABORT, 'EditorialPolicySnapshot is append-only'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_frozen_material_update
                BEFORE UPDATE OF article_id, origin_run_id, revision_no,
                    generation_attempt_id, base_revision_id, provenance_kind,
                    created_by_id, title, summary, body_markdown, body_blocks,
                    claim_bindings, content_hash, input_manifest_hash,
                    claim_manifest_hash, quality_manifest_hash,
                    editorial_policy_snapshot_id, editorial_policy_version,
                    editorial_policy_hash, event_verification_id,
                    verification_manifest, verification_manifest_hash,
                    evidence_manifest, evidence_manifest_hash,
                    exclusion_manifest, exclusion_manifest_hash,
                    visual_manifest, visual_manifest_hash
                ON {revision_table}
                BEGIN SELECT RAISE(ABORT, 'ArticleRevision frozen material is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_append_only_delete
                BEFORE DELETE ON {revision_table}
                BEGIN SELECT RAISE(ABORT, 'ArticleRevision is append-only'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_terminal_projection_update
                BEFORE UPDATE OF claim_graph_state, quality_state,
                    quality_gate_manifest_hash, quality_report_hash,
                    quality_manifest_hash
                ON {revision_table}
                WHEN OLD.claim_graph_state IN ('passed', 'blocked')
                  OR OLD.quality_state IN ('passed', 'failed')
                BEGIN SELECT RAISE(ABORT, 'ArticleRevision terminal projection is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_revalidation_fence_update
                BEFORE UPDATE OF revalidation_event_key,
                    revalidation_generation, revalidation_lease_token
                ON {revision_table}
                WHEN OLD.revalidation_event_key IS NOT NULL
                  OR OLD.claim_graph_state IN ('passed', 'blocked')
                  OR OLD.quality_state IN ('passed', 'failed')
                BEGIN SELECT RAISE(ABORT, 'ArticleRevision revalidation fence is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_attempt_frozen_material_update
                BEFORE UPDATE OF article_id, origin_run_id, generator_name,
                    generator_version, input_manifest_hash,
                    generation_manifest_hash, editorial_policy_snapshot_id,
                    editorial_policy_version, editorial_policy_hash,
                    verification_manifest, verification_manifest_hash,
                    evidence_manifest, evidence_manifest_hash,
                    exclusion_manifest, exclusion_manifest_hash,
                    visual_manifest, visual_manifest_hash,
                    generation_pipeline_manifest_hash
                ON {attempt_table}
                BEGIN SELECT RAISE(ABORT, 'GenerationAttempt frozen material is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_attempt_terminal_projection_update
                BEFORE UPDATE OF state, output_checksum,
                    error_detail_redacted, finished_at
                ON {attempt_table}
                WHEN OLD.state IN ('succeeded', 'failed')
                BEGIN SELECT RAISE(ABORT, 'GenerationAttempt terminal projection is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_attempt_append_only_delete
                BEFORE DELETE ON {attempt_table}
                BEGIN SELECT RAISE(ABORT, 'GenerationAttempt is append-only'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_visualization_render_frozen_update
                BEFORE UPDATE OF revision_id, kind, title, transform_spec,
                    input_manifest_hash, alt_text
                ON {render_table}
                BEGIN SELECT RAISE(ABORT, 'VisualizationRender frozen material is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_visualization_render_terminal_update
                BEFORE UPDATE OF state, object_key, object_version, checksum
                ON {render_table}
                WHEN OLD.state IN ('succeeded', 'failed')
                BEGIN SELECT RAISE(ABORT, 'VisualizationRender terminal projection is immutable'); END;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_visualization_render_append_only_delete
                BEFORE DELETE ON {render_table}
                BEGIN SELECT RAISE(ABORT, 'VisualizationRender is append-only'); END;
            ''')
            for table_name in guarded_tables:
                table = schema_editor.quote_name(table_name)
                cursor.execute(f'''
                    CREATE TRIGGER {table_name}_append_only_update
                    BEFORE UPDATE ON {table}
                    BEGIN SELECT RAISE(ABORT, 'Editorial evaluation rows are append-only'); END;
                ''')
                cursor.execute(f'''
                    CREATE TRIGGER {table_name}_append_only_delete
                    BEFORE DELETE ON {table}
                    BEGIN SELECT RAISE(ABORT, 'Editorial evaluation rows are append-only'); END;
                ''')
            terminal_child_queries = {
                'editorial_claim': 'NEW.revision_id',
                'editorial_claimevidence': (
                    '(SELECT revision_id FROM editorial_claim '
                    'WHERE id = NEW.claim_id)'
                ),
                'editorial_qualitycheck': 'NEW.revision_id',
                'editorial_visualplacement': 'NEW.revision_id',
                'editorial_visualizationrender': 'NEW.revision_id',
            }
            for table_name, revision_expression in terminal_child_queries.items():
                table = schema_editor.quote_name(table_name)
                cursor.execute(f'''
                    CREATE TRIGGER {table_name}_terminal_parent_insert
                    BEFORE INSERT ON {table}
                    WHEN EXISTS (
                        SELECT 1 FROM {revision_table}
                        WHERE id = {revision_expression}
                          AND (claim_graph_state IN ('passed', 'blocked')
                               OR quality_state IN ('passed', 'failed'))
                    )
                    BEGIN SELECT RAISE(ABORT, 'Terminal ArticleRevision cannot accept children'); END;
                ''')
        elif vendor == 'postgresql':
            cursor.execute('''
                CREATE OR REPLACE FUNCTION editorial_reject_append_only_mutation()
                RETURNS trigger AS $$ BEGIN
                    RAISE EXCEPTION 'Editorial row is append-only' USING ERRCODE = '23514';
                END; $$ LANGUAGE plpgsql;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_policy_snapshot_append_only
                BEFORE UPDATE OR DELETE ON {policy_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_reject_append_only_mutation();
            ''')
            cursor.execute('''
                CREATE OR REPLACE FUNCTION editorial_guard_revision_frozen_material()
                RETURNS trigger AS $$ BEGIN
                    IF NEW.title IS DISTINCT FROM OLD.title
                       OR NEW.summary IS DISTINCT FROM OLD.summary
                       OR NEW.body_markdown IS DISTINCT FROM OLD.body_markdown
                       OR NEW.body_blocks IS DISTINCT FROM OLD.body_blocks
                       OR NEW.article_id IS DISTINCT FROM OLD.article_id
                       OR NEW.origin_run_id IS DISTINCT FROM OLD.origin_run_id
                       OR NEW.revision_no IS DISTINCT FROM OLD.revision_no
                       OR NEW.generation_attempt_id IS DISTINCT FROM OLD.generation_attempt_id
                       OR NEW.base_revision_id IS DISTINCT FROM OLD.base_revision_id
                       OR NEW.provenance_kind IS DISTINCT FROM OLD.provenance_kind
                       OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id
                       OR NEW.claim_bindings IS DISTINCT FROM OLD.claim_bindings
                       OR NEW.content_hash IS DISTINCT FROM OLD.content_hash
                       OR NEW.input_manifest_hash IS DISTINCT FROM OLD.input_manifest_hash
                       OR NEW.claim_manifest_hash IS DISTINCT FROM OLD.claim_manifest_hash
                       OR NEW.quality_manifest_hash IS DISTINCT FROM OLD.quality_manifest_hash
                       OR NEW.editorial_policy_snapshot_id IS DISTINCT FROM OLD.editorial_policy_snapshot_id
                       OR NEW.editorial_policy_version IS DISTINCT FROM OLD.editorial_policy_version
                       OR NEW.editorial_policy_hash IS DISTINCT FROM OLD.editorial_policy_hash
                       OR NEW.event_verification_id IS DISTINCT FROM OLD.event_verification_id
                       OR NEW.verification_manifest IS DISTINCT FROM OLD.verification_manifest
                       OR NEW.verification_manifest_hash IS DISTINCT FROM OLD.verification_manifest_hash
                       OR NEW.evidence_manifest IS DISTINCT FROM OLD.evidence_manifest
                       OR NEW.evidence_manifest_hash IS DISTINCT FROM OLD.evidence_manifest_hash
                       OR NEW.exclusion_manifest IS DISTINCT FROM OLD.exclusion_manifest
                       OR NEW.exclusion_manifest_hash IS DISTINCT FROM OLD.exclusion_manifest_hash
                       OR NEW.visual_manifest IS DISTINCT FROM OLD.visual_manifest
                       OR NEW.visual_manifest_hash IS DISTINCT FROM OLD.visual_manifest_hash
                    THEN RAISE EXCEPTION 'ArticleRevision frozen material is immutable' USING ERRCODE = '23514';
                    END IF;
                    IF (OLD.revalidation_event_key IS NOT NULL
                        OR OLD.claim_graph_state IN ('passed', 'blocked')
                        OR OLD.quality_state IN ('passed', 'failed'))
                       AND (NEW.revalidation_event_key IS DISTINCT FROM OLD.revalidation_event_key
                        OR NEW.revalidation_generation IS DISTINCT FROM OLD.revalidation_generation
                        OR NEW.revalidation_lease_token IS DISTINCT FROM OLD.revalidation_lease_token)
                    THEN RAISE EXCEPTION 'ArticleRevision revalidation fence is immutable' USING ERRCODE = '23514';
                    END IF;
                    IF (OLD.claim_graph_state IN ('passed', 'blocked')
                        OR OLD.quality_state IN ('passed', 'failed'))
                       AND (NEW.claim_graph_state IS DISTINCT FROM OLD.claim_graph_state
                        OR NEW.quality_state IS DISTINCT FROM OLD.quality_state
                        OR NEW.quality_gate_manifest_hash IS DISTINCT FROM OLD.quality_gate_manifest_hash
                        OR NEW.quality_report_hash IS DISTINCT FROM OLD.quality_report_hash
                        OR NEW.quality_manifest_hash IS DISTINCT FROM OLD.quality_manifest_hash)
                    THEN RAISE EXCEPTION 'ArticleRevision terminal projection is immutable' USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_frozen_material
                BEFORE UPDATE ON {revision_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_guard_revision_frozen_material();
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_revision_append_only_delete
                BEFORE DELETE ON {revision_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_reject_append_only_mutation();
            ''')
            cursor.execute('''
                CREATE OR REPLACE FUNCTION editorial_guard_attempt_frozen_material()
                RETURNS trigger AS $$ BEGIN
                    IF NEW.article_id IS DISTINCT FROM OLD.article_id
                       OR NEW.origin_run_id IS DISTINCT FROM OLD.origin_run_id
                       OR NEW.generator_name IS DISTINCT FROM OLD.generator_name
                       OR NEW.generator_version IS DISTINCT FROM OLD.generator_version
                       OR NEW.input_manifest_hash IS DISTINCT FROM OLD.input_manifest_hash
                       OR NEW.generation_manifest_hash IS DISTINCT FROM OLD.generation_manifest_hash
                       OR NEW.editorial_policy_snapshot_id IS DISTINCT FROM OLD.editorial_policy_snapshot_id
                       OR NEW.editorial_policy_version IS DISTINCT FROM OLD.editorial_policy_version
                       OR NEW.editorial_policy_hash IS DISTINCT FROM OLD.editorial_policy_hash
                       OR NEW.verification_manifest IS DISTINCT FROM OLD.verification_manifest
                       OR NEW.verification_manifest_hash IS DISTINCT FROM OLD.verification_manifest_hash
                       OR NEW.evidence_manifest IS DISTINCT FROM OLD.evidence_manifest
                       OR NEW.evidence_manifest_hash IS DISTINCT FROM OLD.evidence_manifest_hash
                       OR NEW.exclusion_manifest IS DISTINCT FROM OLD.exclusion_manifest
                       OR NEW.exclusion_manifest_hash IS DISTINCT FROM OLD.exclusion_manifest_hash
                       OR NEW.visual_manifest IS DISTINCT FROM OLD.visual_manifest
                       OR NEW.visual_manifest_hash IS DISTINCT FROM OLD.visual_manifest_hash
                       OR NEW.generation_pipeline_manifest_hash IS DISTINCT FROM OLD.generation_pipeline_manifest_hash
                    THEN RAISE EXCEPTION 'GenerationAttempt frozen material is immutable' USING ERRCODE = '23514';
                    END IF;
                    IF OLD.state IN ('succeeded', 'failed')
                       AND (NEW.state IS DISTINCT FROM OLD.state
                        OR NEW.output_checksum IS DISTINCT FROM OLD.output_checksum
                        OR NEW.error_detail_redacted IS DISTINCT FROM OLD.error_detail_redacted
                        OR NEW.finished_at IS DISTINCT FROM OLD.finished_at)
                    THEN RAISE EXCEPTION 'GenerationAttempt terminal projection is immutable' USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_attempt_frozen_material
                BEFORE UPDATE ON {attempt_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_guard_attempt_frozen_material();
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_attempt_append_only_delete
                BEFORE DELETE ON {attempt_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_reject_append_only_mutation();
            ''')
            cursor.execute('''
                CREATE OR REPLACE FUNCTION editorial_guard_visualization_render()
                RETURNS trigger AS $$ BEGIN
                    IF NEW.revision_id IS DISTINCT FROM OLD.revision_id
                       OR NEW.kind IS DISTINCT FROM OLD.kind
                       OR NEW.title IS DISTINCT FROM OLD.title
                       OR NEW.transform_spec IS DISTINCT FROM OLD.transform_spec
                       OR NEW.input_manifest_hash IS DISTINCT FROM OLD.input_manifest_hash
                       OR NEW.alt_text IS DISTINCT FROM OLD.alt_text
                    THEN RAISE EXCEPTION 'VisualizationRender frozen material is immutable' USING ERRCODE = '23514';
                    END IF;
                    IF OLD.state IN ('succeeded', 'failed')
                       AND (NEW.state IS DISTINCT FROM OLD.state
                        OR NEW.object_key IS DISTINCT FROM OLD.object_key
                        OR NEW.object_version IS DISTINCT FROM OLD.object_version
                        OR NEW.checksum IS DISTINCT FROM OLD.checksum)
                    THEN RAISE EXCEPTION 'VisualizationRender terminal projection is immutable' USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_visualization_render_frozen
                BEFORE UPDATE ON {render_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_guard_visualization_render();
            ''')
            cursor.execute(f'''
                CREATE TRIGGER editorial_visualization_render_append_only_delete
                BEFORE DELETE ON {render_table}
                FOR EACH ROW EXECUTE FUNCTION editorial_reject_append_only_mutation();
            ''')
            cursor.execute('''
                CREATE OR REPLACE FUNCTION editorial_reject_terminal_child_insert()
                RETURNS trigger AS $$
                DECLARE parent_revision uuid;
                BEGIN
                    IF TG_TABLE_NAME = 'editorial_claimevidence' THEN
                        SELECT revision_id INTO parent_revision
                        FROM editorial_claim WHERE id = NEW.claim_id;
                    ELSE
                        parent_revision := NEW.revision_id;
                    END IF;
                    IF EXISTS (
                        SELECT 1 FROM editorial_articlerevision
                        WHERE id = parent_revision
                          AND (claim_graph_state IN ('passed', 'blocked')
                               OR quality_state IN ('passed', 'failed'))
                    ) THEN
                        RAISE EXCEPTION 'Terminal ArticleRevision cannot accept children' USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END; $$ LANGUAGE plpgsql;
            ''')
            for table_name in (*guarded_tables, 'editorial_visualizationrender'):
                table = schema_editor.quote_name(table_name)
                cursor.execute(f'''
                    CREATE TRIGGER {table_name}_terminal_parent_insert
                    BEFORE INSERT ON {table}
                    FOR EACH ROW EXECUTE FUNCTION editorial_reject_terminal_child_insert();
                ''')
            for table_name in guarded_tables:
                table = schema_editor.quote_name(table_name)
                cursor.execute(f'''
                    CREATE TRIGGER {table_name}_append_only
                    BEFORE UPDATE OR DELETE ON {table}
                    FOR EACH ROW EXECUTE FUNCTION editorial_reject_append_only_mutation();
                ''')


def remove_editorial_policy_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'sqlite':
            names = [
                'editorial_policy_snapshot_append_only_update',
                'editorial_policy_snapshot_append_only_delete',
                'editorial_revision_frozen_material_update',
                'editorial_revision_append_only_delete',
                'editorial_revision_terminal_projection_update',
                'editorial_revision_revalidation_fence_update',
                'editorial_attempt_frozen_material_update',
                'editorial_attempt_terminal_projection_update',
                'editorial_attempt_append_only_delete',
                'editorial_visualization_render_frozen_update',
                'editorial_visualization_render_terminal_update',
                'editorial_visualization_render_append_only_delete',
            ]
            for table_name in (
                'editorial_claim', 'editorial_claimevidence',
                'editorial_qualitycheck', 'editorial_visualplacement'
            ):
                names.extend((
                    f'{table_name}_append_only_update',
                    f'{table_name}_append_only_delete',
                    f'{table_name}_terminal_parent_insert',
                ))
            names.append('editorial_visualizationrender_terminal_parent_insert')
            for name in names:
                cursor.execute(f'DROP TRIGGER IF EXISTS {name}')
        elif vendor == 'postgresql':
            cursor.execute('DROP FUNCTION IF EXISTS editorial_guard_attempt_frozen_material() CASCADE')
            cursor.execute('DROP FUNCTION IF EXISTS editorial_guard_revision_frozen_material() CASCADE')
            cursor.execute('DROP FUNCTION IF EXISTS editorial_guard_visualization_render() CASCADE')
            cursor.execute('DROP FUNCTION IF EXISTS editorial_reject_terminal_child_insert() CASCADE')
            cursor.execute('DROP FUNCTION IF EXISTS editorial_reject_append_only_mutation() CASCADE')


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_event_cluster_verification'),
        ('evidence', '0006_generic_evidence_manifest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimevidence',
            old_name='support_kind',
            new_name='relation',
        ),
        migrations.RenameField(
            model_name='qualitycheck',
            old_name='detail',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='qualitycheck',
            old_name='state',
            new_name='result',
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='base_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_revisions', to='editorial.articlerevision'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='origin_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to='collection.collectionrun'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='body_blocks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='claim_graph_state',
            field=models.CharField(default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='claim_bindings',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='editorial_policy_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='editorial_policy_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='event_verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to='editorial.eventclusterverification'),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='evidence_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='evidence_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='visual_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='visual_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='exclusion_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='exclusion_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='quality_gate_manifest_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='quality_report_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='revalidation_event_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='revalidation_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='revalidation_lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='verification_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='verification_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='claim',
            name='block_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_level',
            field=models.CharField(default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='subject_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='claim',
            name='verification_state',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='frozen_material',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='frozen_material_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='source_span',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='source_span_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='claimevidence',
            name='verification_strength',
            field=models.CharField(default='direct', max_length=24),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='editorial_policy_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='origin_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editorial_generation_attempts', to='collection.collectionrun'),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='editorial_policy_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='evidence_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='evidence_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='exclusion_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='exclusion_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='generation_pipeline_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='output_checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='verification_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='verification_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='visual_manifest',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='visual_manifest_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='blocking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='check_version',
            field=models.CharField(default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='details_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visualizationrender',
            name='object_version',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='EditorialPolicySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_code', models.CharField(max_length=40)),
                ('policy_key', models.CharField(max_length=120)),
                ('policy_version', models.CharField(max_length=40)),
                ('document', models.JSONField()),
                ('release_document_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('config_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('implementation_manifest', models.JSONField()),
                ('implementation_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('material_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('topic_code', 'policy_key', 'policy_version'), name='uq_editorial_policy_release_version')],
            },
        ),
        migrations.AddField(
            model_name='articlerevision',
            name='editorial_policy_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to='editorial.editorialpolicysnapshot'),
        ),
        migrations.AddField(
            model_name='generationattempt',
            name='editorial_policy_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generation_attempts', to='editorial.editorialpolicysnapshot'),
        ),
        migrations.CreateModel(
            name='VisualPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_id', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField()),
                ('locator_snapshot', models.JSONField(default=dict)),
                ('rights_status_snapshot', models.CharField(max_length=32)),
                ('rights_basis_url_snapshot', models.URLField(max_length=1000)),
                ('attribution_snapshot', models.TextField(blank=True, null=True)),
                ('alt_text_snapshot', models.TextField()),
                ('caption', models.TextField()),
                ('caption_claim_marker', models.CharField(max_length=30)),
                ('render_object_key_snapshot', models.CharField(blank=True, max_length=1000, null=True)),
                ('render_object_version_snapshot', models.CharField(blank=True, max_length=500, null=True)),
                ('render_checksum_snapshot', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('render_input_manifest_hash_snapshot', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('render_transform_hash_snapshot', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('presentation_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Must be a lowercase SHA-256 hex digest.', regex='^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visual_placements', to='editorial.articlerevision')),
                ('source_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editorial_visual_placements', to='evidence.evidenceasset')),
                ('visualization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='editorial.visualizationrender')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('revision', 'block_id', 'display_order'), name='uq_revision_visual_placement_order'), models.CheckConstraint(condition=models.Q(models.Q(('source_evidence__isnull', False), ('visualization__isnull', True)), models.Q(('source_evidence__isnull', True), ('visualization__isnull', False)), _connector='OR'), name='ck_visual_placement_exactly_one_source')],
            },
        ),
        migrations.RunPython(
            quarantine_legacy_editorial_rows,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='editorial_policy_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to='editorial.editorialpolicysnapshot'),
        ),
        migrations.AlterField(
            model_name='articlerevision',
            name='origin_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_revisions', to='collection.collectionrun'),
        ),
        migrations.AlterField(
            model_name='generationattempt',
            name='editorial_policy_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_attempts', to='editorial.editorialpolicysnapshot'),
        ),
        migrations.AlterField(
            model_name='generationattempt',
            name='origin_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editorial_generation_attempts', to='collection.collectionrun'),
        ),
        migrations.RunPython(
            install_editorial_policy_guards,
            reverse_code=remove_editorial_policy_guards,
        ),
    ]
