# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_key', models.CharField(max_length=200, unique=True)),
                ('topic', models.CharField(db_index=True, max_length=160)),
                ('aggregate_type', models.CharField(max_length=120)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('available_at', 'created_at', 'id'),
                'indexes': [models.Index(fields=['published_at', 'available_at', 'claimed_until'], name='infrastruct_publish_cf9a4f_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='infrastruct_aggrega_38c748_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecretReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=120, unique=True)),
                ('provider', models.CharField(default='env', max_length=32)),
                ('locator', models.CharField(max_length=300)),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'locator', 'version'), name='unique_secret_reference_location')],
            },
        ),
    ]
