# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_version', models.PositiveIntegerField()),
                ('policy_hash', models.CharField(max_length=64)),
                ('cutoff_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('preview', 'Preview'), ('approved', 'Approved'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='preview', max_length=20)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('request_key', models.CharField(max_length=200, unique=True)),
                ('preview_manifest_hash', models.CharField(max_length=64)),
                ('counters', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_detail_redacted', models.CharField(blank=True, max_length=500, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('actor_type', models.CharField(choices=[('admin', 'Admin'), ('system', 'System'), ('worker', 'Worker')], max_length=16)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('entity_type', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('before_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('after_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata_schema_version', models.CharField(max_length=32)),
                ('redaction_policy_version', models.CharField(max_length=64)),
                ('redaction_policy_hash', models.CharField(max_length=64)),
                ('metadata_redacted', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['-occurred_at', '-id'], name='audit_audit_occurre_c896c7_idx'), models.Index(fields=['correlation_id', '-occurred_at'], name='audit_audit_correla_dbd9ca_idx'), models.Index(fields=['entity_type', 'entity_id', '-occurred_at'], name='audit_audit_entity__0b6e19_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('actor_type', 'admin')), models.Q(('actor_type', 'admin'), _negated=True), _connector='OR'), name='audit_admin_actor_required')],
            },
        ),
        migrations.CreateModel(
            name='RetentionBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('object_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('state', models.CharField(choices=[('candidate', 'Candidate'), ('held', 'Held'), ('purged', 'Purged'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='candidate', max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='audit.retentionbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'entity_type', 'entity_id'), name='uq_retention_batch_item')],
            },
        ),
        migrations.CreateModel(
            name='RetentionHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=100)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'active'], name='audit_reten_scope_t_338978_idx')],
            },
        ),
    ]
