# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.CharField(max_length=32, unique=True)),
                ('topic_code', models.CharField(db_index=True, max_length=40)),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('approval_mode', models.CharField(default='manual', max_length=20)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('registry_manifest_hash', models.CharField(max_length=64)),
                ('requested_target_ids', models.JSONField(default=list)),
                ('request_fingerprint', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('queued', '대기'), ('collecting', '수집'), ('extracting', '추출'), ('validating', '검증'), ('drafting', '초안'), ('awaiting_approval', '승인 대기'), ('publishing', '발행'), ('completed', '완료'), ('stopping', '중지 중'), ('stopped', '중지'), ('failed', '실패')], db_index=True, default='queued', max_length=32)),
                ('counters', models.JSONField(default=dict)),
                ('error_summary', models.JSONField(blank=True, null=True)),
                ('stop_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source_registry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.sourceregistrysnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceCollectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_name', models.CharField(max_length=120)),
                ('adapter_version', models.CharField(default='v1', max_length=40)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('response_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_detail_redacted', models.CharField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_attempts', to='collection.collectionrun')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.sourcedefinitionsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=500)),
                ('canonical_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('first_collected_at', models.DateTimeField()),
                ('content_hash', models.CharField(max_length=64)),
                ('source_version_hash', models.CharField(max_length=64)),
                ('body_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('discovery_status', models.CharField(default='active', max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.sourcedefinition')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.sourceitem')),
            ],
        ),
        migrations.CreateModel(
            name='RunSourceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discovery_kind', models.CharField(default='new_version', max_length=24)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_source_items', to='collection.collectionrun')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.sourcedefinitionsnapshot')),
                ('collection_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collection.sourcecollectionattempt')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_links', to='collection.sourceitem')),
            ],
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('input_count', models.PositiveIntegerField(default=0)),
                ('output_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_detail_redacted', models.CharField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='collection.collectionrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'name', 'attempt_no'), name='uq_run_step_attempt')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcecollectionattempt',
            constraint=models.UniqueConstraint(fields=('run', 'source_snapshot'), name='uq_collection_attempt_source'),
        ),
        migrations.AddIndex(
            model_name='sourceitem',
            index=models.Index(fields=['source', 'external_id'], name='collection__source__9f6880_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourceitem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id', 'source_version_hash'), name='uq_source_item_version'),
        ),
        migrations.AddConstraint(
            model_name='runsourceitem',
            constraint=models.UniqueConstraint(fields=('run', 'source_item'), name='uq_run_source_item'),
        ),
    ]
