# Generated by Django 5.2.16 on 2026-08-08 20:09

import hashlib
import hmac
import unicodedata

import rfc8785
from django.db import migrations, models
from django.utils import timezone


def _normalize_json(value):
    if isinstance(value, str):
        return unicodedata.normalize("NFC", value)
    if isinstance(value, dict):
        normalized = {}
        for key, item in value.items():
            normalized_key = unicodedata.normalize("NFC", str(key))
            if normalized_key in normalized:
                raise ValueError("canonical JSON keys collide after NFC normalization")
            normalized[normalized_key] = _normalize_json(item)
        return normalized
    if isinstance(value, (list, tuple)):
        return [_normalize_json(item) for item in value]
    if value is None or isinstance(value, (bool, int, float)):
        return value
    raise TypeError(f"unsupported canonical JSON type: {type(value).__name__}")


def _persisted_material_hash(event):
    material = {
        "event_id": str(event.id),
        "event_type": event.topic,
        "event_version": event.event_version,
        "occurred_at": event.occurred_at.isoformat(),
        "correlation_id": str(event.correlation_id),
        "causation_id": str(event.causation_id) if event.causation_id else None,
        "job_id": str(event.job_id),
        "entity_type": event.aggregate_type,
        "entity_id": str(event.aggregate_id),
        "operation": event.operation,
        "dedupe_key": event.message_key,
        "policy_versions": event.policy_versions,
        "not_before": event.not_before.isoformat(),
        "payload": event.payload,
    }
    return hashlib.sha256(rfc8785.dumps(_normalize_json(material))).hexdigest()


def _exact_event(event, run_id):
    return (
        event.topic == "run.evidence_requested"
        and event.event_version == 1
        and event.operation == "process"
        and event.policy_versions == {}
        and event.aggregate_type == "collection_run"
        and event.aggregate_id == run_id
        and event.job_id == run_id
        and event.message_key == f"run.evidence_requested:{run_id}"
        and event.payload == {"run_id": str(run_id)}
        and hmac.compare_digest(
            event.immutable_material_hash or "",
            _persisted_material_hash(event),
        )
    )


def rearm_legacy_fanout_steps(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    RunStep = apps.get_model("collection", "RunStep")
    CollectionRun = apps.get_model("collection", "CollectionRun")
    OutboxMessage = apps.get_model("infrastructure", "OutboxMessage")
    OutboxConsumerReceipt = apps.get_model(
        "infrastructure", "OutboxConsumerReceipt"
    )
    DocumentExtraction = apps.get_model("evidence", "DocumentExtraction")
    ExtractionRun = apps.get_model("evidence", "ExtractionRun")
    GenericExtractionAttempt = apps.get_model("evidence", "GenericExtractionAttempt")

    def fail_closed(step, *, error_code, detail):
        now = timezone.now()
        step.state = "failed"
        step.error_code = error_code
        step.error_detail_redacted = detail
        step.finished_at = now
        step.recovery_state = "manual_required"
        step.lease_owner = ""
        step.lease_token = None
        step.source_event_id = None
        step.lease_generation = 0
        step.delivery_count = 0
        step.save(using=db_alias)
        CollectionRun.objects.using(db_alias).filter(pk=step.run_id).update(
            state="failed",
            error_summary={"stage": "extract", "code": error_code},
            completed_at=now,
            recovery_state="manual_required",
            next_recovery_at=None,
        )
        DocumentExtraction.objects.using(db_alias).filter(
            run_source_item__run_id=step.run_id,
            state__in=("queued", "running"),
        ).update(
            state="failed",
            document_complete=False,
            error_code=error_code,
            error_detail_redacted=detail,
            finished_at=now,
        )
        GenericExtractionAttempt.objects.using(db_alias).filter(
            run_source_item__run_id=step.run_id,
            state__in=("queued", "running"),
        ).update(
            state="failed",
            error_code=error_code,
            error_detail_redacted=detail,
            finished_at=now,
        )
        ExtractionRun.objects.using(db_alias).filter(
            document_extraction__run_source_item__run_id=step.run_id,
            state__in=("queued", "running"),
        ).update(
            state="failed",
            error_code=error_code,
            error_detail_redacted=detail,
            finished_at=now,
        )

    for step in RunStep.objects.using(db_alias).filter(name="extract").iterator():
        step.lease_owner = ""
        step.lease_token = None
        step.lease_generation = 0
        step.delivery_count = 0
        if step.fanout_completed_at is not None:
            step.state = "succeeded"
            step.save(using=db_alias)
            continue
        if step.state != "running":
            step.save(using=db_alias)
            continue

        events = list(
            OutboxMessage.objects.using(db_alias)
            .filter(message_key=f"run.evidence_requested:{step.run_id}")
            .order_by("created_at", "id")[:2]
        )
        if len(events) != 1 or not _exact_event(events[0], step.run_id):
            fail_closed(
                step,
                error_code="legacy_fanout_identity_ambiguous",
                detail="Legacy fanout event envelope was not exact",
            )
            continue
        event = events[0]
        receipts = list(
            OutboxConsumerReceipt.objects.using(db_alias)
            .filter(event_id=event.id, consumer_name="run-evidence")
            .order_by("id")[:2]
        )
        if len(receipts) != 1:
            fail_closed(
                step,
                error_code="legacy_fanout_receipt_unproven",
                detail="Legacy fanout receipt identity was not exact",
            )
            continue
        receipt = receipts[0]
        now = timezone.now()
        active_dispatch = (
            event.status == "dispatching"
            and event.claimed_until is not None
            and event.claimed_until > now
        )
        active_consumer = (
            receipt.state == "processing"
            and receipt.claimed_until is not None
            and receipt.claimed_until > now
        )
        if active_dispatch or active_consumer:
            raise RuntimeError(
                "drain active evidence fanout deliveries before migration"
            )
        if (
            event.status in ("published", "dead_letter")
            or receipt.state in ("succeeded", "dead_letter")
        ):
            fail_closed(
                step,
                error_code="legacy_fanout_terminal_receipt",
                detail="Terminal legacy fanout delivery cannot be rearmed",
            )
            continue
        if event.status not in ("pending", "dispatching") or receipt.state not in (
            "retry",
            "processing",
        ):
            fail_closed(
                step,
                error_code="legacy_fanout_receipt_unproven",
                detail="Legacy fanout receipt state cannot be safely rearmed",
            )
            continue

        step.source_event_id = event.id
        step.state = "queued"
        step.save(using=db_alias)
        receipt.state = "retry"
        receipt.attempts = 0
        receipt.last_error_code = "deployment_recovery_generation_fence"
        receipt.next_retry_at = None
        receipt.completed_at = None
        receipt.dead_lettered_at = None
        receipt.claimed_at = None
        receipt.claimed_until = None
        receipt.lease_token = None
        receipt.save(using=db_alias)
        event.status = "pending"
        event.published_at = None
        event.available_at = now
        event.max_attempts = max(event.max_attempts, event.attempts + 1)
        event.last_error_code = "deployment_recovery_generation_fence"
        event.last_error_at = now
        event.dead_lettered_at = None
        event.claimed_at = None
        event.claimed_until = None
        event.lease_owner = ""
        event.lease_token = None
        event.save(using=db_alias)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0008_source_access_policy_runtime"),
        ("evidence", "0004_extractionprofiledecision_report_envelope"),
        ("infrastructure", "0002_outboxconsumerreceipt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runstep",
            name="delivery_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="runstep",
            name="lease_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="runstep",
            name="lease_owner",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="runstep",
            name="lease_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runstep",
            name="source_event_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(rearm_legacy_fanout_steps, noop_reverse),
        migrations.AddConstraint(
            model_name="runstep",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state="running",
                        source_event_id__isnull=False,
                        lease_generation__gt=0,
                        delivery_count=models.F("lease_generation"),
                        lease_token__isnull=False,
                    )
                    & ~models.Q(lease_owner="")
                    | ~models.Q(state="running")
                    & models.Q(lease_owner="", lease_token__isnull=True)
                ),
                name="ck_run_step_lease_complete",
            ),
        ),
    ]
