# Generated by Django 5.2.16 on 2026-08-08 20:07

import django.core.validators
import django.utils.timezone
import hashlib
import hmac
import json
import unicodedata
import uuid
import rfc8785
from django.db import migrations, models


TERMINAL_STATES = ("succeeded", "low_confidence", "failed")


def _normalize_json(value):
    if isinstance(value, str):
        return unicodedata.normalize("NFC", value)
    if isinstance(value, dict):
        normalized = {}
        for key, item in value.items():
            normalized_key = unicodedata.normalize("NFC", str(key))
            if normalized_key in normalized:
                raise ValueError("canonical JSON keys collide after NFC normalization")
            normalized[normalized_key] = _normalize_json(item)
        return normalized
    if isinstance(value, (list, tuple)):
        return [_normalize_json(item) for item in value]
    if value is None or isinstance(value, (bool, int, float)):
        return value
    raise TypeError(f"unsupported canonical JSON type: {type(value).__name__}")


def _persisted_material_hash(event):
    material = {
        "event_id": str(event.id),
        "event_type": event.topic,
        "event_version": event.event_version,
        "occurred_at": event.occurred_at.isoformat(),
        "correlation_id": str(event.correlation_id),
        "causation_id": str(event.causation_id) if event.causation_id else None,
        "job_id": str(event.job_id),
        "entity_type": event.aggregate_type,
        "entity_id": str(event.aggregate_id),
        "operation": event.operation,
        "dedupe_key": event.message_key,
        "policy_versions": event.policy_versions,
        "not_before": event.not_before.isoformat(),
        "payload": event.payload,
    }
    return hashlib.sha256(rfc8785.dumps(_normalize_json(material))).hexdigest()


def _lease_condition():
    return (
        models.Q(
            state="running",
            source_event_id__isnull=False,
            lease_generation__gt=0,
            delivery_count=models.F("lease_generation"),
            lease_token__isnull=False,
        )
        & ~models.Q(lease_owner="")
        | ~models.Q(state="running")
        & models.Q(lease_owner="", lease_token__isnull=True)
    )


def _terminal_condition():
    return (
        models.Q(
            state__in=("queued", "running"),
            terminal_event_key__isnull=True,
            terminal_state__isnull=True,
        )
        | models.Q(
            state__in=("succeeded", "low_confidence"),
            terminal_event_key__isnull=False,
            terminal_state="ready",
        )
        | models.Q(
            state="failed",
            terminal_event_key__isnull=False,
            terminal_state="failed",
        )
    )


def backfill_extraction_envelopes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    DocumentExtraction = apps.get_model("evidence", "DocumentExtraction")
    ExtractionRun = apps.get_model("evidence", "ExtractionRun")
    GenericExtractionAttempt = apps.get_model("evidence", "GenericExtractionAttempt")
    EvidenceAsset = apps.get_model("evidence", "EvidenceAsset")
    ExtractionProfileSnapshot = apps.get_model(
        "evidence", "ExtractionProfileSnapshot"
    )
    OutboxMessage = apps.get_model("infrastructure", "OutboxMessage")
    OutboxConsumerReceipt = apps.get_model(
        "infrastructure", "OutboxConsumerReceipt"
    )
    CollectionRun = apps.get_model("collection", "CollectionRun")
    RunStep = apps.get_model("collection", "RunStep")
    RunSourceItem = apps.get_model("collection", "RunSourceItem")

    run_source_items = {
        item.id: item
        for item in RunSourceItem.objects.using(db_alias).all()
    }
    failed_run_ids = set()

    def fail_run(run_source_item_id, *, error_code, detail):
        run_source_item = run_source_items.get(run_source_item_id)
        if run_source_item is None:
            return
        run_id = run_source_item.run_id
        now = django.utils.timezone.now()
        CollectionRun.objects.using(db_alias).filter(pk=run_id).update(
            state="failed",
            error_summary={"stage": "extract", "code": error_code},
            completed_at=now,
            recovery_state="manual_required",
            next_recovery_at=None,
        )
        RunStep.objects.using(db_alias).filter(
            run_id=run_id,
            name="extract",
            attempt_no=1,
        ).update(
            state="failed",
            error_code=error_code,
            error_detail_redacted=detail,
            finished_at=now,
            recovery_state="manual_required",
            lease_owner="",
            lease_token=None,
        )
        failed_run_ids.add(run_id)

    def canonical(value):
        def normalize(item):
            if isinstance(item, str):
                return unicodedata.normalize("NFC", item)
            if isinstance(item, dict):
                return {
                    unicodedata.normalize("NFC", str(key)): normalize(child)
                    for key, child in item.items()
                }
            if isinstance(item, list):
                return [normalize(child) for child in item]
            return item

        encoded = rfc8785.dumps(normalize(value))
        return hashlib.sha256(encoded).hexdigest()

    def event_material_exact(
        event,
        *,
        topic,
        aggregate_type,
        aggregate_id,
        message_key,
        run_id,
    ):
        return (
            event.topic == topic
            and event.event_version == 1
            and event.operation == "process"
            and event.policy_versions == {}
            and event.aggregate_type == aggregate_type
            and event.aggregate_id == aggregate_id
            and event.message_key == message_key
            and event.job_id == run_id
            and isinstance(event.payload, dict)
            and hmac.compare_digest(
                event.immutable_material_hash or "",
                _persisted_material_hash(event),
            )
        )

    def ready_message(
        topic,
        aggregate_id,
        payload_key,
        *,
        aggregate_type,
        message_key,
        run_id,
    ):
        messages = list(
            OutboxMessage.objects.using(db_alias)
            .filter(message_key=message_key)
            .order_by("created_at", "id")[:2]
        )
        if len(messages) != 1:
            return None
        message = messages[0]
        payload = message.payload if isinstance(message.payload, dict) else {}
        if not event_material_exact(
            message,
            topic=topic,
            aggregate_type=aggregate_type,
            aggregate_id=aggregate_id,
            message_key=message_key,
            run_id=run_id,
        ) or str(payload.get(payload_key)) != str(aggregate_id):
            return None
        return message

    def rearm_requested_event(
        *,
        topic,
        aggregate_type,
        aggregate_id,
        message_key,
        run_id,
        expected_payload,
        consumer_name,
    ):
        messages = list(
            OutboxMessage.objects.using(db_alias)
            .filter(message_key=message_key)
            .order_by("created_at", "id")[:2]
        )
        if len(messages) != 1:
            return None
        event = messages[0]
        if not event_material_exact(
            event,
            topic=topic,
            aggregate_type=aggregate_type,
            aggregate_id=aggregate_id,
            message_key=message_key,
            run_id=run_id,
        ) or event.payload != expected_payload:
            return None
        receipts = list(
            OutboxConsumerReceipt.objects.using(db_alias)
            .filter(event_id=event.id, consumer_name=consumer_name)
            .order_by("id")[:2]
        )
        if len(receipts) != 1:
            return None
        receipt = receipts[0]
        now = django.utils.timezone.now()
        active_dispatch = (
            event.status == "dispatching"
            and event.claimed_until is not None
            and event.claimed_until > now
        )
        active_consumer = (
            receipt.state == "processing"
            and receipt.claimed_until is not None
            and receipt.claimed_until > now
        )
        if active_dispatch or active_consumer:
            raise RuntimeError(
                "drain active evidence extraction deliveries before migration"
            )
        if (
            event.status in ("published", "dead_letter")
            or receipt.state in ("succeeded", "dead_letter")
        ):
            return ("terminal", event)
        if event.status not in ("pending", "dispatching") or receipt.state not in (
            "retry",
            "processing",
        ):
            return None
        event.status = "pending"
        event.published_at = None
        event.available_at = now
        event.max_attempts = max(event.max_attempts, event.attempts + 1)
        event.last_error_code = "deployment_recovery_generation_fence"
        event.last_error_at = now
        event.dead_lettered_at = None
        event.claimed_at = None
        event.claimed_until = None
        event.lease_owner = ""
        event.lease_token = None
        event.save(using=db_alias)
        receipt.state = "retry"
        receipt.attempts = 0
        receipt.last_error_code = "deployment_recovery_generation_fence"
        receipt.next_retry_at = None
        receipt.completed_at = None
        receipt.dead_lettered_at = None
        receipt.claimed_at = None
        receipt.claimed_until = None
        receipt.lease_token = None
        receipt.save(using=db_alias)
        return ("rearmed", event)

    documents = {
        document.id: document
        for document in DocumentExtraction.objects.using(db_alias).all()
    }
    valid_children = set()
    profiles = {
        profile.id: profile
        for profile in ExtractionProfileSnapshot.objects.using(db_alias).all()
    }
    for child in ExtractionRun.objects.using(db_alias).all().iterator():
        child.lease_owner = ""
        child.lease_token = None
        if child.state == "running":
            child.state = "queued"
            child.lease_generation = 0
            child.delivery_count = 0
            child.parent_lease_generation = 0
        elif child.state in ("succeeded", "low_confidence"):
            parent = documents[child.document_extraction_id]
            profile = profiles[child.extraction_profile_snapshot_id]
            evidence_rows = list(
                EvidenceAsset.objects.using(db_alias)
                .filter(extraction_run_id=child.id)
                .order_by("id")
            )
            requested_pages = set(child.requested_page_indices or [])
            proven = bool(evidence_rows) and all(
                evidence.document_extraction_id == parent.id
                and evidence.source_item_id == parent.source_item_id
                and evidence.origin_run_source_item_id == parent.run_source_item_id
                and evidence.extraction_result_checksum == child.result_checksum
                and evidence.parent_asset_id == parent.input_asset_id
                and evidence.extraction_method == child.engine
                and evidence.extractor_version == child.package_version
                and evidence.extraction_config_hash == child.config_hash
                and isinstance(evidence.locator, dict)
                and evidence.locator.get("page_index") in requested_pages
                for evidence in evidence_rows
            ) and (
                child.profile_key == profile.profile_key
                and child.profile_version == profile.profile_version
                and child.config_hash == profile.config_hash
                and child.profile_material_hash == profile.profile_material_hash
                and sorted(set(child.requested_page_indices or []))
                == sorted(set(child.processed_page_indices or []))
            )
            if proven:
                manifest = sorted(
                    (
                        {
                            "source_item_id": str(evidence.source_item_id),
                            "origin_run_source_item_id": str(
                                evidence.origin_run_source_item_id
                            ),
                            "parent_asset_id": (
                                str(evidence.parent_asset_id)
                                if evidence.parent_asset_id else None
                            ),
                            "document_extraction_id": str(
                                evidence.document_extraction_id
                            ),
                            "extraction_run_id": str(evidence.extraction_run_id),
                            "extraction_profile_snapshot_id": str(
                                child.extraction_profile_snapshot_id
                            ),
                            "profile_material_hash": child.profile_material_hash,
                            "extraction_method": evidence.extraction_method,
                            "extractor_version": evidence.extractor_version,
                            "extraction_config_hash": (
                                evidence.extraction_config_hash
                            ),
                            "result_checksum": (
                                evidence.extraction_result_checksum
                            ),
                            "page_index": evidence.locator.get("page_index"),
                            "evidence_content_hash": evidence.evidence_content_hash,
                            "locator_hash": canonical(evidence.locator),
                        }
                        for evidence in evidence_rows
                    ),
                    key=lambda entry: (
                        entry["locator_hash"], entry["evidence_content_hash"]
                    ),
                )
                child.expected_evidence_count = len(evidence_rows)
                child.expected_evidence_manifest_hash = canonical(manifest)
                child.terminal_event_key = f"legacy:child-ready:{child.id}"
                child.terminal_state = "ready"
                valid_children.add(child.id)
            else:
                child.state = "failed"
                child.error_code = "legacy_evidence_manifest_unproven"
                child.error_detail_redacted = (
                    "Historical child evidence provenance could not be proven"
                )
                child.terminal_event_key = f"legacy:child-failed:{child.id}"
                child.terminal_state = "failed"
                fail_run(
                    parent.run_source_item_id,
                    error_code="legacy_evidence_manifest_unproven",
                    detail="Historical child evidence provenance could not be proven",
                )
        elif child.state == "failed":
            child.terminal_event_key = f"legacy:child-failed:{child.id}"
            child.terminal_state = "failed"
        if child.parent_lease_generation > 0:
            parent = documents[child.document_extraction_id]
            if child.parent_lease_generation != parent.lease_generation:
                child.parent_lease_generation = 0
            else:
                child.source_event_id = parent.source_event_id
        child.save(using=db_alias)

    for document in documents.values():
        document_run_id = run_source_items[document.run_source_item_id].run_id
        document.lease_owner = ""
        document.lease_token = None
        if document.state == "running":
            recovery = rearm_requested_event(
                topic="evidence.document_route_requested",
                aggregate_type="document_extraction",
                aggregate_id=document.id,
                message_key=f"evidence.document_route_requested:{document.id}",
                run_id=document_run_id,
                expected_payload={
                    "run_id": str(document_run_id),
                    "run_source_item_id": str(document.run_source_item_id),
                    "source_item_id": str(document.source_item_id),
                    "input_asset_id": (
                        str(document.input_asset_id)
                        if document.input_asset_id else None
                    ),
                    "input_kind": document.input_kind,
                    "document_extraction_id": str(document.id),
                    "input_checksum": document.input_checksum,
                },
                consumer_name="document-extraction",
            )
            if recovery is not None and recovery[0] == "rearmed":
                event = recovery[1]
                document.state = "queued"
                document.source_event_id = event.id
                document.lease_generation = 0
                document.delivery_count = 0
            else:
                document.state = "failed"
                document.error_code = "legacy_delivery_identity_unproven"
                document.error_detail_redacted = (
                    "Historical document delivery could not be safely rearmed"
                )
                document.terminal_event_key = f"legacy:document-failed:{document.id}"
                document.terminal_state = "failed"
                fail_run(
                    document.run_source_item_id,
                    error_code="legacy_delivery_identity_unproven",
                    detail="Historical document delivery could not be safely rearmed",
                )
        elif document.state in ("succeeded", "low_confidence"):
            message = ready_message(
                "evidence.document_ready",
                document.id,
                "document_extraction_id",
                aggregate_type="DocumentExtraction",
                message_key=(
                    f"evidence.document_ready:{document.id}:"
                    f"{document.selected_evidence_manifest_hash}"
                ),
                run_id=document_run_id,
            )
            payload = message.payload if message else {}
            selected_ids = {
                str(page.get("selected_run_id"))
                for page in (
                    document.routing_manifest.get("pages", [])
                    if isinstance(document.routing_manifest, dict)
                    else []
                )
                if isinstance(page, dict) and page.get("selected_run_id")
            }
            routing_pages = (
                document.routing_manifest.get("pages", [])
                if isinstance(document.routing_manifest, dict)
                else []
            )
            routing_indices = sorted(
                page.get("page_index")
                for page in routing_pages
                if isinstance(page, dict)
                and type(page.get("page_index")) is int
            )
            proven = bool(message and selected_ids) and (
                routing_indices == list(range(document.input_page_count))
            ) and all(
                str(child_id) in {str(value) for value in valid_children}
                for child_id in selected_ids
            ) and (
                str(payload.get("run_source_item_id"))
                == str(document.run_source_item_id)
                and str(payload.get("source_item_id")) == str(document.source_item_id)
                and payload.get("input_page_count") == document.input_page_count
                and payload.get("coverage_manifest_hash")
                == document.coverage_manifest_hash
                and payload.get("selected_evidence_manifest_hash")
                == document.selected_evidence_manifest_hash
                and payload.get("document_complete") is True
            )
            if proven:
                document.terminal_event_key = message.message_key
                document.terminal_state = "ready"
            else:
                document.state = "failed"
                document.document_complete = False
                document.error_code = "legacy_ready_identity_unproven"
                document.error_detail_redacted = (
                    "Historical document-ready identity could not be proven"
                )
                document.terminal_event_key = f"legacy:document-failed:{document.id}"
                document.terminal_state = "failed"
                fail_run(
                    document.run_source_item_id,
                    error_code="legacy_ready_identity_unproven",
                    detail="Historical document-ready identity could not be proven",
                )
            if proven and message.causation_id:
                document.source_event_id = message.causation_id
        elif document.state == "failed":
            document.terminal_event_key = f"legacy:document-failed:{document.id}"
            document.terminal_state = "failed"
        document.save(using=db_alias)

    for attempt in GenericExtractionAttempt.objects.using(db_alias).all().iterator():
        attempt_run_id = run_source_items[attempt.run_source_item_id].run_id
        attempt.lease_owner = ""
        attempt.lease_token = None
        if attempt.state == "running":
            recovery = rearm_requested_event(
                topic="evidence.other_extract_requested",
                aggregate_type="generic_extraction_attempt",
                aggregate_id=attempt.id,
                message_key=f"evidence.other_extract_requested:{attempt.id}",
                run_id=attempt_run_id,
                expected_payload={
                    "run_id": str(attempt_run_id),
                    "run_source_item_id": str(attempt.run_source_item_id),
                    "source_item_id": str(attempt.source_item_id),
                    "input_asset_id": (
                        str(attempt.input_asset_id) if attempt.input_asset_id else None
                    ),
                    "generic_extraction_attempt_id": str(attempt.id),
                    "profile_snapshot_id": str(
                        attempt.extraction_profile_snapshot_id
                    ),
                    "profile_material_hash": attempt.profile_material_hash,
                    "engine": attempt.engine,
                    "extractor_version": attempt.extractor_version,
                    "config_hash": attempt.config_hash,
                    "validation_mode": attempt.validation_mode,
                    "calibration_profile_key": attempt.calibration_profile_key,
                    "calibration_profile_version": attempt.calibration_profile_version,
                    "calibration_profile_hash": attempt.calibration_profile_hash,
                    "fingerprint_schema_version": attempt.fingerprint_schema_version,
                    "extraction_fingerprint": attempt.extraction_fingerprint,
                },
                consumer_name="generic-extraction",
            )
            if recovery is not None and recovery[0] == "rearmed":
                event = recovery[1]
                attempt.state = "queued"
                attempt.source_event_id = event.id
                attempt.lease_generation = 0
                attempt.delivery_count = 0
            else:
                attempt.state = "failed"
                attempt.error_code = "legacy_delivery_identity_unproven"
                attempt.error_detail_redacted = (
                    "Historical generic delivery could not be safely rearmed"
                )
                attempt.terminal_event_key = f"legacy:other-failed:{attempt.id}"
                attempt.terminal_state = "failed"
                fail_run(
                    attempt.run_source_item_id,
                    error_code="legacy_delivery_identity_unproven",
                    detail="Historical generic delivery could not be safely rearmed",
                )
        elif attempt.state in ("succeeded", "low_confidence"):
            message = ready_message(
                "evidence.other_ready", attempt.id,
                "generic_extraction_attempt_id",
                aggregate_type="GenericExtractionAttempt",
                message_key=f"evidence.other_ready:{attempt.id}:{attempt.result_checksum}",
                run_id=attempt_run_id,
            )
            payload = message.payload if message else {}
            evidence = (
                EvidenceAsset.objects.using(db_alias)
                .filter(pk=attempt.evidence_asset_id)
                .first()
                if attempt.evidence_asset_id
                else None
            )
            proven = bool(message and evidence) and (
                evidence.generic_extraction_attempt_id == attempt.id
                and evidence.source_item_id == attempt.source_item_id
                and evidence.origin_run_source_item_id == attempt.run_source_item_id
                and evidence.parent_asset_id == attempt.input_asset_id
                and evidence.extraction_result_checksum == attempt.result_checksum
                and str(payload.get("evidence_asset_id")) == str(evidence.id)
                and str(payload.get("run_source_item_id"))
                == str(attempt.run_source_item_id)
                and str(payload.get("source_item_id")) == str(attempt.source_item_id)
                and payload.get("engine") == attempt.engine
                and payload.get("result_checksum") == attempt.result_checksum
                and payload.get("extraction_fingerprint")
                == attempt.extraction_fingerprint
            )
            if proven:
                attempt.terminal_event_key = message.message_key
                attempt.terminal_state = "ready"
            else:
                attempt.state = "failed"
                attempt.error_code = "legacy_ready_identity_unproven"
                attempt.error_detail_redacted = (
                    "Historical other-ready identity could not be proven"
                )
                attempt.terminal_event_key = f"legacy:other-failed:{attempt.id}"
                attempt.terminal_state = "failed"
                fail_run(
                    attempt.run_source_item_id,
                    error_code="legacy_ready_identity_unproven",
                    detail="Historical other-ready identity could not be proven",
                )
            if proven and message.causation_id:
                attempt.source_event_id = message.causation_id
        elif attempt.state == "failed":
            attempt.terminal_event_key = f"legacy:other-failed:{attempt.id}"
            attempt.terminal_state = "failed"
        attempt.save(using=db_alias)

    if failed_run_ids:
        for document in DocumentExtraction.objects.using(db_alias).all().iterator():
            run_id = run_source_items[document.run_source_item_id].run_id
            if run_id in failed_run_ids and document.state in ("queued", "running"):
                document.state = "failed"
                document.document_complete = False
                document.error_code = "migration_manual_recovery_required"
                document.error_detail_redacted = (
                    "Collection extraction recovery requires manual intervention"
                )
                document.finished_at = django.utils.timezone.now()
                document.lease_owner = ""
                document.lease_token = None
                document.terminal_event_key = f"legacy:document-failed:{document.id}"
                document.terminal_state = "failed"
                document.save(using=db_alias)
        for attempt in GenericExtractionAttempt.objects.using(db_alias).all().iterator():
            run_id = run_source_items[attempt.run_source_item_id].run_id
            if run_id in failed_run_ids and attempt.state in ("queued", "running"):
                attempt.state = "failed"
                attempt.error_code = "migration_manual_recovery_required"
                attempt.error_detail_redacted = (
                    "Collection extraction recovery requires manual intervention"
                )
                attempt.finished_at = django.utils.timezone.now()
                attempt.lease_owner = ""
                attempt.lease_token = None
                attempt.terminal_event_key = f"legacy:other-failed:{attempt.id}"
                attempt.terminal_state = "failed"
                attempt.save(using=db_alias)
        for child in ExtractionRun.objects.using(db_alias).all().iterator():
            parent = documents[child.document_extraction_id]
            run_id = run_source_items[parent.run_source_item_id].run_id
            if run_id in failed_run_ids and child.state in ("queued", "running"):
                child.state = "failed"
                child.error_code = "migration_manual_recovery_required"
                child.error_detail_redacted = (
                    "Collection extraction recovery requires manual intervention"
                )
                child.finished_at = django.utils.timezone.now()
                child.lease_owner = ""
                child.lease_token = None
                child.terminal_event_key = f"legacy:child-failed:{child.id}"
                child.terminal_state = "failed"
                child.save(using=db_alias)


def noop_reverse(apps, schema_editor):
    pass


def create_parent_generation_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for action in ("INSERT", "UPDATE"):
            schema_editor.execute(
                f"""
                CREATE TRIGGER evidence_extractionrun_parent_generation_{action.lower()}
                BEFORE {action} ON evidence_extractionrun
                FOR EACH ROW
                WHEN NEW.parent_lease_generation > 0
                 AND NOT EXISTS (
                    SELECT 1
                      FROM evidence_documentextraction parent
                     WHERE parent.id = NEW.document_extraction_id
                       AND parent.lease_generation = NEW.parent_lease_generation
                       AND (
                            parent.source_event_id = NEW.source_event_id
                            OR (
                                parent.source_event_id IS NULL
                                AND NEW.source_event_id IS NULL
                            )
                       )
                 )
                BEGIN
                    SELECT RAISE(ABORT, 'stale extraction parent generation');
                END;
                """
            )
        schema_editor.execute(
            """
            CREATE TRIGGER evidence_documentextraction_rebind_active_children
            AFTER UPDATE OF lease_generation, source_event_id
            ON evidence_documentextraction
            FOR EACH ROW
            WHEN NEW.lease_generation IS NOT OLD.lease_generation
              OR NEW.source_event_id IS NOT OLD.source_event_id
            BEGIN
                UPDATE evidence_extractionrun
                   SET parent_lease_generation = NEW.lease_generation,
                       source_event_id = NEW.source_event_id,
                       state = 'queued',
                       lease_owner = '',
                       lease_token = NULL,
                       next_retry_at = NULL
                 WHERE document_extraction_id = NEW.id
                   AND state IN ('queued', 'running');
            END;
            """
        )
    elif vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION evidence_check_extractionrun_parent_generation()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.parent_lease_generation > 0 AND NOT EXISTS (
                    SELECT 1
                      FROM evidence_documentextraction parent
                     WHERE parent.id = NEW.document_extraction_id
                       AND parent.lease_generation = NEW.parent_lease_generation
                       AND parent.source_event_id IS NOT DISTINCT FROM NEW.source_event_id
                ) THEN
                    RAISE EXCEPTION 'stale extraction parent generation';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER evidence_extractionrun_parent_generation
            BEFORE INSERT OR UPDATE ON evidence_extractionrun
            FOR EACH ROW
            EXECUTE FUNCTION evidence_check_extractionrun_parent_generation();

            CREATE FUNCTION evidence_rebind_extractionrun_parent_generation()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.lease_generation IS DISTINCT FROM OLD.lease_generation
                   OR NEW.source_event_id IS DISTINCT FROM OLD.source_event_id
                THEN
                    UPDATE evidence_extractionrun
                       SET parent_lease_generation = NEW.lease_generation,
                           source_event_id = NEW.source_event_id,
                           state = 'queued',
                           lease_owner = '',
                           lease_token = NULL,
                           next_retry_at = NULL
                     WHERE document_extraction_id = NEW.id
                       AND state IN ('queued', 'running');
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER evidence_documentextraction_rebind_active_children
            AFTER UPDATE OF lease_generation, source_event_id
            ON evidence_documentextraction
            FOR EACH ROW
            EXECUTE FUNCTION evidence_rebind_extractionrun_parent_generation();
            """
        )


def drop_parent_generation_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS "
            "evidence_documentextraction_rebind_active_children;"
        )
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS evidence_extractionrun_parent_generation_insert;"
        )
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS evidence_extractionrun_parent_generation_update;"
        )
    elif vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS "
            "evidence_documentextraction_rebind_active_children "
            "ON evidence_documentextraction;"
        )
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS "
            "evidence_rebind_extractionrun_parent_generation();"
        )
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS evidence_extractionrun_parent_generation "
            "ON evidence_extractionrun;"
        )
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS evidence_check_extractionrun_parent_generation();"
        )


def create_terminal_identity_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    tables = (
        "evidence_documentextraction",
        "evidence_extractionrun",
        "evidence_genericextractionattempt",
    )
    if vendor == "sqlite":
        for table in tables:
            schema_editor.execute(
                f"""
                CREATE TRIGGER {table}_terminal_identity_immutable
                BEFORE UPDATE ON {table}
                FOR EACH ROW
                WHEN OLD.terminal_event_key IS NOT NULL
                 AND (
                    NEW.terminal_event_key IS NOT OLD.terminal_event_key
                    OR NEW.terminal_state IS NOT OLD.terminal_state
                    OR NEW.state IS NOT OLD.state
                 )
                BEGIN
                    SELECT RAISE(ABORT, 'immutable extraction terminal identity');
                END;
                """
            )
    elif vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION evidence_reject_terminal_identity_change()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.terminal_event_key IS NOT NULL AND (
                    NEW.terminal_event_key IS DISTINCT FROM OLD.terminal_event_key
                    OR NEW.terminal_state IS DISTINCT FROM OLD.terminal_state
                    OR NEW.state IS DISTINCT FROM OLD.state
                ) THEN
                    RAISE EXCEPTION 'immutable extraction terminal identity';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table in tables:
            schema_editor.execute(
                f"""
                CREATE TRIGGER {table}_terminal_identity_immutable
                BEFORE UPDATE ON {table}
                FOR EACH ROW
                EXECUTE FUNCTION evidence_reject_terminal_identity_change();
                """
            )


def drop_terminal_identity_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    tables = (
        "evidence_documentextraction",
        "evidence_extractionrun",
        "evidence_genericextractionattempt",
    )
    for table in tables:
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {table}_terminal_identity_immutable"
            + (f" ON {table};" if vendor == "postgresql" else ";")
        )
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS evidence_reject_terminal_identity_change();"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_run_step_generation_fencing'),
        ('evidence', '0004_extractionprofiledecision_report_envelope'),
        ('infrastructure', '0002_outboxconsumerreceipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceasset',
            name='low_confidence_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='delivery_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='lease_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='source_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='terminal_event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='documentextraction',
            name='terminal_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='delivery_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='expected_evidence_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='expected_evidence_manifest_hash',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Expected a lowercase SHA-256 digest')]),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='lease_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='parent_lease_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='source_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='terminal_event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='extractionrun',
            name='terminal_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='delivery_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='lease_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='lease_owner',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='lease_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='source_event_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='terminal_event_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genericextractionattempt',
            name='terminal_state',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='ExtractionObjectWriteReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_kind', models.CharField(max_length=32)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('source_event_id', models.UUIDField(db_index=True)),
                ('lease_generation', models.PositiveBigIntegerField()),
                ('lease_identity_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('purpose', models.CharField(choices=[('raw', 'Raw input'), ('result', 'Extraction result'), ('reason', 'Low-confidence reason'), ('converted', 'Converted document')], max_length=24)),
                ('object_key', models.CharField(max_length=1024)),
                ('state', models.CharField(choices=[('reserved', 'Reserved'), ('uploaded', 'Uploaded'), ('bound', 'Bound'), ('orphaned', 'Orphaned')], default='reserved', max_length=16)),
                ('object_version', models.CharField(blank=True, max_length=256, null=True)),
                ('object_etag', models.CharField(blank=True, max_length=256, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[a-f0-9]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('orphaned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('aggregate_kind', 'aggregate_id', 'lease_generation', 'purpose', 'object_key'), name='uq_extraction_object_write_generation'),
                    models.CheckConstraint(
                        condition=(
                            models.Q(state='reserved', object_version__isnull=True, object_etag__isnull=True, checksum__isnull=True, byte_size__isnull=True, content_type__isnull=True, uploaded_at__isnull=True, bound_at__isnull=True, orphaned_at__isnull=True)
                            | models.Q(state='uploaded', object_version__isnull=False, checksum__isnull=False, byte_size__isnull=False, content_type__isnull=False, uploaded_at__isnull=False, bound_at__isnull=True, orphaned_at__isnull=True)
                            | models.Q(state='bound', object_version__isnull=False, checksum__isnull=False, byte_size__isnull=False, content_type__isnull=False, uploaded_at__isnull=False, bound_at__isnull=False, orphaned_at__isnull=True)
                            | models.Q(state='orphaned', object_version__isnull=True, object_etag__isnull=True, checksum__isnull=True, byte_size__isnull=True, content_type__isnull=True, uploaded_at__isnull=True, bound_at__isnull=True, orphaned_at__isnull=False)
                            | models.Q(state='orphaned', object_version__isnull=False, checksum__isnull=False, byte_size__isnull=False, content_type__isnull=False, uploaded_at__isnull=False, bound_at__isnull=True, orphaned_at__isnull=False)
                        ),
                        name='ck_extraction_object_write_state',
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_extraction_envelopes, noop_reverse),
        migrations.AddConstraint(
            model_name='documentextraction',
            constraint=models.CheckConstraint(condition=_lease_condition(), name='ck_document_extraction_lease_complete'),
        ),
        migrations.AddConstraint(
            model_name='documentextraction',
            constraint=models.CheckConstraint(condition=_terminal_condition(), name='ck_document_extraction_terminal_complete'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.CheckConstraint(condition=_lease_condition(), name='ck_extraction_run_lease_complete'),
        ),
        migrations.AddConstraint(
            model_name='extractionrun',
            constraint=models.CheckConstraint(condition=_terminal_condition(), name='ck_extraction_run_terminal_complete'),
        ),
        migrations.AddConstraint(
            model_name='genericextractionattempt',
            constraint=models.CheckConstraint(condition=_lease_condition(), name='ck_generic_extraction_lease_complete'),
        ),
        migrations.AddConstraint(
            model_name='genericextractionattempt',
            constraint=models.CheckConstraint(condition=_terminal_condition(), name='ck_generic_extraction_terminal_complete'),
        ),
        migrations.RunPython(
            create_parent_generation_triggers,
            drop_parent_generation_triggers,
        ),
        migrations.RunPython(
            create_terminal_identity_triggers,
            drop_terminal_identity_triggers,
        ),
    ]
