# Generated by Django 5.2.16 on 2026-08-09

import hashlib
import math
import re
import unicodedata
import uuid

import django.core.validators
import django.utils.timezone
from django.db import migrations, models

import rfc8785


def _canonical_hash(value):
    def normalize(item):
        if isinstance(item, str):
            return unicodedata.normalize("NFC", item)
        if isinstance(item, dict):
            return {
                unicodedata.normalize("NFC", str(key)): normalize(child)
                for key, child in item.items()
            }
        if isinstance(item, list):
            return [normalize(child) for child in item]
        return item

    return hashlib.sha256(rfc8785.dumps(normalize(value))).hexdigest()


def _content_hash(evidence):
    return _canonical_hash({
        "text": evidence.extracted_text,
        "structured_data": evidence.structured_data,
        "object_checksum": evidence.checksum,
    })


def _review_hash(evidence, attempt, source_snapshot_id):
    return _canonical_hash({
        "review_subject_schema_version": "v1",
        "evidence_asset_id": str(evidence.id),
        "source_item_id": str(evidence.source_item_id) if evidence.source_item_id else None,
        "origin_run_source_item_id": (
            str(evidence.origin_run_source_item_id)
            if evidence.origin_run_source_item_id else None
        ),
        "source_snapshot_id": str(source_snapshot_id) if source_snapshot_id else None,
        "input_checksum": evidence.checksum,
        "derivation_type": evidence.derivation_type,
        "kind": evidence.kind,
        "locator_type": evidence.locator_type,
        "locator": evidence.locator,
        "evidence_content_hash": evidence.evidence_content_hash,
        "confidence": str(evidence.confidence) if evidence.confidence is not None else None,
        "confidence_detail_hash": _canonical_hash(evidence.confidence_detail),
        "document": None,
        "generic": {
            "generic_extraction_attempt_id": str(attempt.id),
            "extraction_fingerprint": attempt.extraction_fingerprint,
            "engine": attempt.engine,
            "extractor_version": attempt.extractor_version,
            "config_hash": attempt.config_hash,
            "validation_mode": attempt.validation_mode,
            "result_checksum": attempt.result_checksum,
            "low_confidence_reasons_hash": attempt.low_confidence_reasons_hash,
            "calibration_profile_key": attempt.calibration_profile_key,
            "calibration_profile_version": attempt.calibration_profile_version,
            "calibration_profile_hash": attempt.calibration_profile_hash,
        },
    })


def _finite_number(value):
    if isinstance(value, bool):
        return False
    try:
        return math.isfinite(float(value))
    except (TypeError, ValueError, OverflowError):
        return False


def _valid_bbox(value):
    return bool(
        isinstance(value, (list, tuple))
        and len(value) == 4
        and all(_finite_number(item) for item in value)
        and float(value[2]) > float(value[0])
        and float(value[3]) > float(value[1])
    )


def _valid_polygon(value):
    if not isinstance(value, (list, tuple)) or len(value) < 3:
        return False
    points = []
    for point in value:
        if (
            not isinstance(point, (list, tuple))
            or len(point) != 2
            or not all(_finite_number(item) for item in point)
        ):
            return False
        points.append((float(point[0]), float(point[1])))
    return len(set(points)) >= 3


def _sha256(value):
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


def _canonical_uuid(value):
    try:
        return isinstance(value, str) and str(uuid.UUID(value)) == value
    except (ValueError, AttributeError):
        return False


def _locator_is_proven(evidence, attempt):
    locator = evidence.locator
    if not isinstance(locator, dict) or locator.get("locator_type") != evidence.locator_type:
        return False
    nonempty = lambda key: isinstance(locator.get(key), str) and bool(locator[key].strip())
    region = _valid_bbox(locator.get("bbox")) or _valid_polygon(locator.get("polygon"))
    if evidence.locator_type == "html_dom":
        css = nonempty("css_selector")
        xpath = nonempty("xpath")
        return css != xpath and not set(locator) - {"locator_type", "css_selector", "xpath"}
    if evidence.locator_type == "structured_path":
        return (
            locator.get("path_type") in {"json_pointer", "xpath", "jsonpath"}
            and isinstance(locator.get("path"), str)
            and bool(locator["path"].strip())
            and not set(locator) - {"locator_type", "path_type", "path"}
        )
    if evidence.locator_type == "spreadsheet_cell":
        return (
            nonempty("sheet_name")
            and nonempty("cell_range")
            and not set(locator) - {"locator_type", "sheet_name", "cell_range"}
        )
    if evidence.locator_type == "hwpx_path":
        allowed = {
            "locator_type", "section_path", "paragraph_id", "table_id",
            "row_index", "column_index", "embedded_object_id",
        }
        paragraph = nonempty("paragraph_id")
        table = nonempty("table_id")
        embedded = nonempty("embedded_object_id")
        row = locator.get("row_index")
        column = locator.get("column_index")
        variants = (
            paragraph and not table and not embedded and row is None and column is None,
            table and not paragraph and not embedded and type(row) is int and row >= 0
            and type(column) is int and column >= 0,
            embedded and not paragraph and not table and row is None and column is None,
        )
        return bool(
            not set(locator) - allowed
            and isinstance(locator.get("section_path"), str)
            and re.fullmatch(r"Contents/section[0-9]+\.xml", locator["section_path"])
            and sum(bool(item) for item in variants) == 1
        )
    if evidence.locator_type == "hwp_conversion":
        allowed = {
            "locator_type",
            "attempt_id", "generation", "nonce", "input_checksum", "input_byte_size",
            "output_pdf_checksum", "output_pdf_byte_size", "converter_manifest_hash",
            "sandbox_report_hash", "page_count",
        }
        structured = evidence.structured_data
        try:
            records = structured["records"]
            record = records[0]
            report = record["structured_data"]["conversion_report"]
        except (KeyError, IndexError, TypeError):
            return False
        report_fields = {
            "schema_version", "protocol_version", "attempt_id", "generation", "nonce",
            "input_checksum_sha256", "input_byte_size", "output_pdf_checksum_sha256",
            "output_pdf_byte_size", "page_count", "pdf_mime", "qpdf_validated",
            "converter_manifest_hash", "sandbox_policy", "warnings", "font_substitutions",
            "fallback_used", "partial_text_used", "stdout_evidence_used",
        }
        try:
            report_hash = _canonical_hash(report)
        except (TypeError, ValueError):
            return False
        return bool(
            set(locator) == allowed
            and isinstance(records, list) and len(records) == 1
            and record.get("locator") == locator
            and set(report) == report_fields
            and locator.get("attempt_id") == str(attempt.id)
            and _canonical_uuid(locator.get("attempt_id"))
            and locator.get("generation") == 1
            and _sha256(locator.get("nonce"))
            and _sha256(locator.get("input_checksum"))
            and type(locator.get("input_byte_size")) is int
            and locator["input_byte_size"] > 0
            and _sha256(locator.get("output_pdf_checksum"))
            and type(locator.get("output_pdf_byte_size")) is int
            and locator["output_pdf_byte_size"] > 0
            and _sha256(locator.get("converter_manifest_hash"))
            and _sha256(locator.get("sandbox_report_hash"))
            and type(locator.get("page_count")) is int
            and locator["page_count"] > 0
            and report.get("schema_version") == "v1"
            and report.get("protocol_version") == "wisdome-hwp-uds-v1"
            and report.get("attempt_id") == locator["attempt_id"]
            and report.get("generation") == 1
            and report.get("nonce") == locator["nonce"]
            and report.get("input_checksum_sha256") == locator["input_checksum"]
            and report.get("input_byte_size") == locator["input_byte_size"]
            and report.get("output_pdf_checksum_sha256") == locator["output_pdf_checksum"]
            and report.get("output_pdf_byte_size") == locator["output_pdf_byte_size"]
            and report.get("converter_manifest_hash") == locator["converter_manifest_hash"]
            and report.get("page_count") == locator["page_count"]
            and report.get("pdf_mime") == "application/pdf"
            and report.get("qpdf_validated") is True
            and locator.get("sandbox_report_hash") == report_hash
            and evidence.mime_type == "application/pdf"
            and evidence.object_key
            and evidence.object_version
            and evidence.checksum == locator["output_pdf_checksum"]
            and evidence.byte_size == locator["output_pdf_byte_size"]
        )
    if evidence.locator_type == "image_region":
        return bool(
            not set(locator) - {"locator_type", "bbox", "polygon", "page_index", "frame_index"}
            and region
            and (
                locator.get("page_index") is None
                or type(locator.get("page_index")) is int and locator["page_index"] >= 0
            )
            and (
                locator.get("frame_index") is None
                or type(locator.get("frame_index")) is int and locator["frame_index"] >= 0
            )
        )
    if evidence.locator_type == "media_time":
        start = locator.get("start_seconds")
        end = locator.get("end_seconds")
        return bool(
            not set(locator) - {"locator_type", "start_seconds", "end_seconds", "track_id"}
            and _finite_number(start) and _finite_number(end)
            and 0 <= float(start) < float(end)
        )
    if evidence.locator_type == "manual":
        return bool(
            not set(locator) - {"locator_type", "entry_id", "actor_id", "source_url"}
            and nonempty("entry_id") and nonempty("actor_id") and nonempty("source_url")
        )
    return False


def _confidence_is_proven(evidence, attempt):
    attempt_calibration = (
        attempt.calibration_profile_key,
        attempt.calibration_profile_version,
        attempt.calibration_profile_hash,
    )
    evidence_calibration = (
        evidence.calibration_profile_key,
        evidence.calibration_profile_version,
        evidence.calibration_profile_hash,
    )
    calibrated = attempt.validation_mode == "calibrated"
    if calibrated != all(attempt_calibration) or calibrated != all(evidence_calibration):
        return False
    if calibrated:
        return (
            evidence.confidence is not None
            and _finite_number(evidence.confidence)
            and 0 <= float(evidence.confidence) <= 1
        )
    return evidence.confidence is None and not any(evidence_calibration)


def _publishable_is_proven(evidence, attempt):
    expected = bool(
        evidence.rights_status in {"allowed", "attribution_required"}
        and evidence.rights_basis_url
        and (
            evidence.rights_status != "attribution_required"
            or evidence.attribution_text
        )
        and (
            evidence.kind not in {"image", "chart", "screenshot"}
            or evidence.alt_text
        )
        and not evidence.manual_review_required
        and evidence.review_state in {"passed", "pending"}
        and attempt.state != "low_confidence"
    )
    return evidence.publishable == expected


def backfill_generic_evidence_manifests(apps, schema_editor):
    alias = schema_editor.connection.alias
    Attempt = apps.get_model("evidence", "GenericExtractionAttempt")
    Evidence = apps.get_model("evidence", "EvidenceAsset")
    Document = apps.get_model("evidence", "DocumentExtraction")
    Child = apps.get_model("evidence", "ExtractionRun")
    RunSourceItem = apps.get_model("collection", "RunSourceItem")
    CollectionRun = apps.get_model("collection", "CollectionRun")
    RunStep = apps.get_model("collection", "RunStep")
    Profile = apps.get_model("evidence", "ExtractionProfileSnapshot")
    Reservation = apps.get_model("evidence", "ExtractionObjectWriteReservation")
    run_source_items = {
        item.id: item
        for item in RunSourceItem.objects.using(alias).all().iterator()
    }
    failed_run_ids = set()
    empty_manifest_hash = _canonical_hash([])
    profiles = {
        item.id: item
        for item in Profile.objects.using(alias).all().iterator()
    }

    for attempt in Attempt.objects.using(alias).filter(
        state__in=("succeeded", "low_confidence")
    ).iterator():
        evidence_rows = list(
            Evidence.objects.using(alias)
            .filter(generic_extraction_attempt_id=attempt.id)
            .order_by("id")
        )
        evidence = evidence_rows[0] if len(evidence_rows) == 1 else None
        run_source_item = run_source_items.get(attempt.run_source_item_id)
        profile = profiles.get(attempt.extraction_profile_snapshot_id)
        engine_locators = {
            "html_parser": {"html_dom"},
            "structured_parser": {"structured_path"},
            "spreadsheet_parser": {"spreadsheet_cell"},
            "hwpx_parser": {"hwpx_path"},
            "legacy_hwp_converter": {"hwp_conversion"},
            "browser_capture": {"image_region"},
            "media_parser": {"image_region", "media_time"},
            "manual_entry": {"manual"},
        }
        proof_checks = {
            "terminal": bool(
                attempt.terminal_event_key
                and attempt.terminal_state == "ready"
                and _sha256(attempt.result_checksum)
                and (
                    attempt.state != "low_confidence"
                    or attempt.validation_mode == "calibrated"
                )
            ),
            "single": bool(evidence),
            "anchor": bool(evidence) and attempt.evidence_asset_id == evidence.id,
            "source": bool(evidence) and evidence.source_item_id == attempt.source_item_id,
            "origin": bool(evidence) and evidence.origin_run_source_item_id == attempt.run_source_item_id,
            "parent": bool(evidence) and evidence.parent_asset_id == attempt.input_asset_id,
            "engine": bool(evidence) and evidence.extraction_method == attempt.engine,
            "extractor": bool(evidence) and evidence.extractor_version == attempt.extractor_version,
            "config": bool(evidence) and evidence.extraction_config_hash == attempt.config_hash,
            "mode": bool(evidence) and evidence.validation_mode == attempt.validation_mode,
            "result": bool(evidence) and evidence.extraction_result_checksum == attempt.result_checksum,
            "profile": profile is not None and (
                attempt.profile_material_hash == profile.profile_material_hash
                and attempt.engine == profile.engine
                and attempt.extractor_version == profile.extractor_version
                and attempt.config_hash == profile.config_hash
                and attempt.validation_mode == profile.validation_mode
                and attempt.calibration_profile_key == profile.calibration_profile_key
                and attempt.calibration_profile_version == profile.calibration_profile_version
                and attempt.calibration_profile_hash == profile.calibration_profile_hash
            ),
            "calibration": bool(evidence) and (
                evidence.calibration_profile_key == attempt.calibration_profile_key
                and evidence.calibration_profile_version == attempt.calibration_profile_version
                and evidence.calibration_profile_hash == attempt.calibration_profile_hash
            ),
            "content": bool(evidence) and evidence.evidence_content_hash == _content_hash(evidence),
            "review": bool(evidence) and evidence.review_subject_hash == _review_hash(
                evidence,
                attempt,
                run_source_item.source_snapshot_id if run_source_item else None,
            ),
            "locator": bool(evidence) and (
                evidence.locator_type in engine_locators.get(attempt.engine, set())
                and _locator_is_proven(evidence, attempt)
            ),
            "confidence": bool(evidence) and _confidence_is_proven(evidence, attempt),
            "publishable": bool(evidence) and _publishable_is_proven(evidence, attempt),
        }
        proven = all(proof_checks.values())
        if proven:
            entry = {
                "evidence_asset_id": str(evidence.id),
                "source_item_id": str(evidence.source_item_id),
                "origin_run_source_item_id": str(evidence.origin_run_source_item_id),
                "parent_asset_id": str(evidence.parent_asset_id) if evidence.parent_asset_id else None,
                "generic_extraction_attempt_id": str(evidence.generic_extraction_attempt_id),
                "extraction_profile_snapshot_id": str(attempt.extraction_profile_snapshot_id),
                "profile_material_hash": attempt.profile_material_hash,
                "kind": evidence.kind,
                "locator_type": evidence.locator_type,
                "locator_hash": _canonical_hash(evidence.locator),
                "extraction_method": evidence.extraction_method,
                "extractor_version": evidence.extractor_version,
                "extraction_config_hash": evidence.extraction_config_hash,
                "validation_mode": evidence.validation_mode,
                "result_checksum": evidence.extraction_result_checksum,
                "evidence_content_hash": evidence.evidence_content_hash,
                "review_subject_hash": evidence.review_subject_hash,
                "calibration_profile_key": evidence.calibration_profile_key,
                "calibration_profile_version": evidence.calibration_profile_version,
                "calibration_profile_hash": evidence.calibration_profile_hash,
                "confidence": str(evidence.confidence) if evidence.confidence is not None else None,
                "object_key": evidence.object_key,
                "object_version": evidence.object_version,
                "checksum": evidence.checksum,
            }
            attempt.expected_evidence_count = 1
            attempt.expected_evidence_manifest_hash = _canonical_hash([entry])
            attempt.save(
                using=alias,
                update_fields=("expected_evidence_count", "expected_evidence_manifest_hash"),
            )
            continue
        attempt.expected_evidence_count = 0
        attempt.expected_evidence_manifest_hash = empty_manifest_hash
        attempt.error_code = "legacy_generic_manifest_unproven"
        failed_checks = ",".join(key for key, passed in proof_checks.items() if not passed)
        attempt.error_detail_redacted = (
            f"Historical generic evidence requires manual recovery: {failed_checks}"
        )[:1000]
        attempt.save(
            using=alias,
            update_fields=(
                "expected_evidence_count",
                "expected_evidence_manifest_hash",
                "error_code",
                "error_detail_redacted",
            ),
        )
        Evidence.objects.using(alias).filter(
            generic_extraction_attempt_id=attempt.id
        ).update(
            publishable=False,
            manual_review_required=True,
            review_state="manual_required",
        )
        if run_source_item is not None:
            failed_run_ids.add(run_source_item.run_id)

    if not failed_run_ids:
        return
    now = django.utils.timezone.now()
    active_states = (
        "queued", "collecting", "extracting", "validating", "drafting",
        "awaiting_approval", "publishing", "stopping",
    )
    CollectionRun.objects.using(alias).filter(
        pk__in=failed_run_ids,
        state__in=active_states,
    ).update(
        state="failed",
        error_summary={"stage": "extract", "code": "legacy_generic_manifest_unproven"},
        completed_at=now,
        recovery_state="manual_required",
        next_recovery_at=None,
    )
    CollectionRun.objects.using(alias).filter(
        pk__in=failed_run_ids,
        state__in=("completed", "stopped", "failed"),
    ).update(
        recovery_state="manual_required",
        next_recovery_at=None,
    )
    RunStep.objects.using(alias).filter(
        run_id__in=failed_run_ids,
        name="extract",
        attempt_no=1,
    ).exclude(state__in=("succeeded", "failed", "stopped")).update(
        state="failed",
        error_code="legacy_generic_manifest_unproven",
        error_detail_redacted="Historical generic evidence manifest could not be proven",
        finished_at=now,
        recovery_state="manual_required",
        lease_owner="",
        lease_token=None,
    )
    RunStep.objects.using(alias).filter(
        run_id__in=failed_run_ids,
        name="extract",
        attempt_no=1,
        state__in=("succeeded", "failed", "stopped"),
    ).update(recovery_state="manual_required")
    for attempt in Attempt.objects.using(alias).filter(
        run_source_item__run_id__in=failed_run_ids,
        state__in=("queued", "running"),
    ).iterator():
        attempt.state = "failed"
        attempt.error_code = "migration_manual_recovery_required"
        attempt.error_detail_redacted = "Collection extraction recovery requires manual intervention"
        attempt.finished_at = now
        attempt.next_retry_at = None
        attempt.lease_owner = ""
        attempt.lease_token = None
        attempt.terminal_event_key = f"migration:generic-failed:{attempt.id}"
        attempt.terminal_state = "failed"
        attempt.save(using=alias)
    for document in Document.objects.using(alias).filter(
        run_source_item__run_id__in=failed_run_ids,
        state__in=("queued", "running"),
    ).iterator():
        document.state = "failed"
        document.document_complete = False
        document.error_code = "migration_manual_recovery_required"
        document.error_detail_redacted = "Collection extraction recovery requires manual intervention"
        document.finished_at = now
        document.next_retry_at = None
        document.lease_owner = ""
        document.lease_token = None
        document.terminal_event_key = f"migration:document-failed:{document.id}"
        document.terminal_state = "failed"
        document.save(using=alias)
    for child in Child.objects.using(alias).filter(
        document_extraction__run_source_item__run_id__in=failed_run_ids,
        state__in=("queued", "running"),
    ).iterator():
        child.state = "failed"
        child.error_code = "migration_manual_recovery_required"
        child.error_detail_redacted = "Collection extraction recovery requires manual intervention"
        child.finished_at = now
        child.next_retry_at = None
        child.lease_owner = ""
        child.lease_token = None
        child.terminal_event_key = f"migration:child-failed:{child.id}"
        child.terminal_state = "failed"
        child.save(using=alias)

    current_generations = {}
    for step in RunStep.objects.using(alias).filter(
        run_id__in=failed_run_ids,
        name="extract",
        attempt_no=1,
    ).iterator():
        current_generations[("fanout", step.run_id)] = step.lease_generation
    for attempt in Attempt.objects.using(alias).filter(
        run_source_item__run_id__in=failed_run_ids
    ).iterator():
        current_generations[("generic", attempt.id)] = attempt.lease_generation
    for document in Document.objects.using(alias).filter(
        run_source_item__run_id__in=failed_run_ids
    ).iterator():
        current_generations[("document", document.id)] = document.lease_generation
    for child in Child.objects.using(alias).filter(
        document_extraction__run_source_item__run_id__in=failed_run_ids
    ).iterator():
        current_generations[("extraction_run", child.id)] = child.lease_generation
    for reservation in Reservation.objects.using(alias).filter(
        state__in=("reserved", "uploaded")
    ).iterator():
        expected_generation = current_generations.get(
            (reservation.aggregate_kind, reservation.aggregate_id)
        )
        if expected_generation is None or reservation.lease_generation != expected_generation:
            continue
        reservation.state = "orphaned"
        reservation.orphaned_at = now
        reservation.save(using=alias, update_fields=("state", "orphaned_at"))


def recreate_generic_terminal_trigger(apps, schema_editor):
    table = "evidence_genericextractionattempt"
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {table}_terminal_identity_immutable;"
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_terminal_identity_immutable
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            WHEN OLD.terminal_event_key IS NOT NULL
             AND (
                NEW.terminal_event_key IS NOT OLD.terminal_event_key
                OR NEW.terminal_state IS NOT OLD.terminal_state
                OR NEW.state IS NOT OLD.state
             )
            BEGIN
                SELECT RAISE(ABORT, 'immutable extraction terminal identity');
            END;
            """
        )
    elif vendor == "postgresql":
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {table}_terminal_identity_immutable ON {table};"
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table}_terminal_identity_immutable
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION evidence_reject_terminal_identity_change();
            """
        )


def drop_generic_terminal_trigger(apps, schema_editor):
    table = "evidence_genericextractionattempt"
    vendor = schema_editor.connection.vendor
    schema_editor.execute(
        f"DROP TRIGGER IF EXISTS {table}_terminal_identity_immutable"
        + (f" ON {table};" if vendor == "postgresql" else ";")
    )


def create_generic_manifest_terminal_trigger(apps, schema_editor):
    table = "evidence_genericextractionattempt"
    trigger = f"{table}_terminal_identity_immutable"
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger};")
        schema_editor.execute(
            f"""
            CREATE TRIGGER {trigger}
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            WHEN OLD.terminal_event_key IS NOT NULL
             AND (
                NEW.terminal_event_key IS NOT OLD.terminal_event_key
                OR NEW.terminal_state IS NOT OLD.terminal_state
                OR NEW.state IS NOT OLD.state
                OR NEW.expected_evidence_count IS NOT OLD.expected_evidence_count
                OR NEW.expected_evidence_manifest_hash IS NOT OLD.expected_evidence_manifest_hash
             )
            BEGIN
                SELECT RAISE(ABORT, 'immutable generic extraction terminal envelope');
            END;
            """
        )
    elif vendor == "postgresql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {trigger} ON {table};")
        schema_editor.execute(
            """
            CREATE OR REPLACE FUNCTION evidence_reject_generic_terminal_change()
            RETURNS trigger AS $$
            BEGIN
                IF OLD.terminal_event_key IS NOT NULL AND (
                    NEW.terminal_event_key IS DISTINCT FROM OLD.terminal_event_key
                    OR NEW.terminal_state IS DISTINCT FROM OLD.terminal_state
                    OR NEW.state IS DISTINCT FROM OLD.state
                    OR NEW.expected_evidence_count IS DISTINCT FROM OLD.expected_evidence_count
                    OR NEW.expected_evidence_manifest_hash IS DISTINCT FROM OLD.expected_evidence_manifest_hash
                ) THEN
                    RAISE EXCEPTION 'immutable generic extraction terminal envelope';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {trigger}
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION evidence_reject_generic_terminal_change();
            """
        )


def restore_shared_generic_terminal_trigger(apps, schema_editor):
    table = "evidence_genericextractionattempt"
    trigger = f"{table}_terminal_identity_immutable"
    vendor = schema_editor.connection.vendor
    schema_editor.execute(
        f"DROP TRIGGER IF EXISTS {trigger}"
        + (f" ON {table};" if vendor == "postgresql" else ";")
    )
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS evidence_reject_generic_terminal_change();"
        )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {trigger}
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION evidence_reject_terminal_identity_change();
            """
        )
    elif vendor == "sqlite":
        schema_editor.execute(
            f"""
            CREATE TRIGGER {trigger}
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            WHEN OLD.terminal_event_key IS NOT NULL
             AND (
                NEW.terminal_event_key IS NOT OLD.terminal_event_key
                OR NEW.terminal_state IS NOT OLD.terminal_state
                OR NEW.state IS NOT OLD.state
             )
            BEGIN
                SELECT RAISE(ABORT, 'immutable extraction terminal identity');
            END;
            """
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_run_step_generation_fencing'),
        ('evidence', '0005_extraction_generation_fencing'),
    ]

    operations = [
        migrations.RunPython(noop, recreate_generic_terminal_trigger),
        migrations.AddField(
            model_name="genericextractionattempt",
            name="expected_evidence_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="genericextractionattempt",
            name="expected_evidence_manifest_hash",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-f0-9]{64}$", "Expected a lowercase SHA-256 digest"
                    )
                ],
            ),
        ),
        migrations.RunPython(backfill_generic_evidence_manifests, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="genericextractionattempt",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(state__in=("succeeded", "low_confidence"))
                    | models.Q(
                        expected_evidence_count__isnull=False,
                        expected_evidence_manifest_hash__isnull=False,
                    )
                ),
                name="ck_generic_terminal_manifest",
            ),
        ),
        migrations.RunPython(
            create_generic_manifest_terminal_trigger,
            restore_shared_generic_terminal_trigger,
        ),
    ]
