# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KillSwitchDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_version', models.PositiveIntegerField()),
                ('enabled', models.BooleanField()),
                ('request_key', models.CharField(max_length=200, unique=True)),
                ('reason', models.CharField(max_length=500)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalControl',
            fields=[
                ('key', models.CharField(default='global_kill_switch', max_length=100, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='True blocks all new external writes and dispatches.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                ('topic_code', models.CharField(max_length=40)),
                ('cron_expression', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='Asia/Seoul', max_length=100)),
                ('window_minutes', models.PositiveIntegerField(default=1440)),
                ('target_ids', models.JSONField(default=list)),
                ('approval_mode', models.CharField(default='manual', max_length=20)),
                ('overlap_policy', models.CharField(choices=[('skip', '건너뛰기'), ('queue_one', '한 건 대기')], default='skip', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_version', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('tick_key', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('skipped', '건너뜀'), ('queued', '대기'), ('dispatched', '실행'), ('coalesced', '병합')], max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coalesced_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduling.scheduledispatch')),
                ('collection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collection.collectionrun')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='scheduling.schedule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule', 'scheduled_for'), name='uq_schedule_tick'), models.UniqueConstraint(condition=models.Q(('state', 'queued')), fields=('schedule',), name='uq_schedule_single_queued')],
            },
        ),
    ]
