# Generated by Django 5.2.16 on 2026-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='auto_publish_activation_refs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='schedule',
            name='auto_publish_validation_refs',
            field=models.JSONField(default=list),
        ),
    ]
