# Generated by Django 5.2.16 on 2026-08-11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _noop(_apps, _schema_editor):
    return None


def _refuse_populated_reverse(apps, schema_editor):
    ScheduleDispatch = apps.get_model("scheduling", "ScheduleDispatch")
    if ScheduleDispatch.objects.using(schema_editor.connection.alias).exists():
        raise migrations.IrreversibleError(
            "ScheduleDispatch frozen execution material cannot be discarded."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_schedule_auto_publish_activation_refs_and_more"),
        ("topics", "0004_semiconductor_source_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledispatch",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatches",
                to="scheduling.schedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="activation_refs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="approval_mode_snapshot",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="coalesced_tick_manifest_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="coalesced_tick_refs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="dispatched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="execution_material",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="execution_material_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="material_version",
            field=models.CharField(
                default="legacy-unverifiable-v1",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="registry_manifest_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="run_request_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="schedule_material",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="schedule_material_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="source_registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_dispatches",
                to="topics.sourceregistrysnapshot",
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="target_snapshot_refs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="tick_set_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="topic_policy_hash",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$",
                        "Expected a lowercase SHA-256 digest",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="topic_policy_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="validation_refs",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_dispatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledispatch",
            name="topic_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_dispatches",
                to="topics.topicpolicy",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledispatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("tick_set_version__gt", 0)),
                name="ck_schedule_dispatch_tick_set_version_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledispatch",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("material_version", "schedule-dispatch-material-v1"))
                    | (
                        models.Q(("source_registry__isnull", False))
                        & models.Q(("topic_policy__isnull", False))
                        & models.Q(("topic_policy_version__isnull", False))
                        & models.Q(("requested_by__isnull", False))
                        & ~models.Q(("schedule_material_hash", ""))
                        & ~models.Q(("registry_manifest_hash", ""))
                        & ~models.Q(("topic_policy_hash", ""))
                        & ~models.Q(("coalesced_tick_manifest_hash", ""))
                    )
                ),
                name="ck_schedule_dispatch_current_material_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledispatch",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(
                        ("material_version", "schedule-dispatch-material-v1"),
                        ("state", "dispatched"),
                    )
                    | (
                        models.Q(("execution_material__isnull", False))
                        & models.Q(("collection_run__isnull", False))
                        & models.Q(("dispatched_at__isnull", False))
                        & ~models.Q(("execution_material_hash", ""))
                        & ~models.Q(("run_request_fingerprint", ""))
                    )
                ),
                name="ck_schedule_dispatch_execution_complete",
            ),
        ),
        migrations.RunPython(_noop, reverse_code=_refuse_populated_reverse),
    ]
