# Generated by Django 5.2.16 on 2026-08-10 14:58

import django.core.validators
import django.db.models.deletion
import hashlib
import json
import uuid
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


SQLITE_GUARD_SQL = (
    """
    CREATE TRIGGER pub_asset_cohort_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedassetcohort
    BEGIN SELECT RAISE(ABORT, 'published asset cohort is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_ao_del_t022
    BEFORE DELETE ON publishing_publishedassetcohort
    BEGIN SELECT RAISE(ABORT, 'published asset cohort is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedevidencesnapshot
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_del_t022
    BEFORE DELETE ON publishing_publishedevidencesnapshot
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedvisualizationsnapshot
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_del_t022
    BEFORE DELETE ON publishing_publishedvisualizationsnapshot
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedvisualizationinput
    BEGIN SELECT RAISE(ABORT, 'published visualization input is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_del_t022
    BEFORE DELETE ON publishing_publishedvisualizationinput
    BEGIN SELECT RAISE(ABORT, 'published visualization input is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_insert_t022
    BEFORE INSERT ON publishing_publishedassetcohort
    WHEN json_valid(NEW.manifest) <> 1
      OR json_type(NEW.manifest) <> 'array'
      OR json_array_length(NEW.manifest) <> NEW.item_count
    BEGIN SELECT RAISE(ABORT, 'published asset cohort manifest count mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_insert_t022
    BEFORE INSERT ON publishing_publishedevidencesnapshot
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN evidence_evidenceasset evidence
            ON evidence.id = NEW.evidence_id
          JOIN collection_sourceitem source_item
            ON source_item.id = evidence.source_item_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id = NEW.evidence_id
           AND placement.visualization_id IS NULL
           AND evidence.source_item_id = NEW.source_item_id
           AND source_item.source_version_hash = NEW.source_version_hash
    )
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot cohort revision mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationsnapshot
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN editorial_visualizationrender visualization
            ON visualization.id = NEW.visualization_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id IS NULL
           AND placement.visualization_id = NEW.visualization_id
           AND visualization.revision_id = cohort.revision_id
    )
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot cohort revision mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationinput
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedvisualizationsnapshot visualization
          JOIN publishing_publishedevidencesnapshot evidence
            ON evidence.id = NEW.evidence_snapshot_id
         WHERE visualization.id = NEW.visualization_snapshot_id
           AND visualization.cohort_id = evidence.cohort_id
    )
    BEGIN SELECT RAISE(ABORT, 'published visualization input cohort mismatch'); END;
    """,
)


POSTGRES_GUARD_SQL = (
    """
    CREATE OR REPLACE FUNCTION publishing_asset_append_only_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'published asset snapshot is append-only';
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedassetcohort
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedevidencesnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedvisualizationsnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedvisualizationinput
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_asset_cohort_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF jsonb_typeof(NEW.manifest) IS DISTINCT FROM 'array'
         OR jsonb_array_length(NEW.manifest) IS DISTINCT FROM NEW.item_count THEN
        RAISE EXCEPTION 'published asset cohort manifest count mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_insert_t022
    BEFORE INSERT ON publishing_publishedassetcohort
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_cohort_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_evidence_snap_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN evidence_evidenceasset evidence
            ON evidence.id = NEW.evidence_id
          JOIN collection_sourceitem source_item
            ON source_item.id = evidence.source_item_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id = NEW.evidence_id
           AND placement.visualization_id IS NULL
           AND evidence.source_item_id = NEW.source_item_id
           AND source_item.source_version_hash = NEW.source_version_hash
      ) THEN
        RAISE EXCEPTION 'published evidence snapshot cohort revision mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_insert_t022
    BEFORE INSERT ON publishing_publishedevidencesnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_evidence_snap_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_visual_snap_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN editorial_visualizationrender visualization
            ON visualization.id = NEW.visualization_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id IS NULL
           AND placement.visualization_id = NEW.visualization_id
           AND visualization.revision_id = cohort.revision_id
      ) THEN
        RAISE EXCEPTION 'published visualization snapshot cohort revision mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_visual_snap_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationsnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_visual_snap_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_visual_input_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedvisualizationsnapshot visualization
          JOIN publishing_publishedevidencesnapshot evidence
            ON evidence.id = NEW.evidence_snapshot_id
         WHERE visualization.id = NEW.visualization_snapshot_id
           AND visualization.cohort_id = evidence.cohort_id
      ) THEN
        RAISE EXCEPTION 'published visualization input cohort mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_visual_input_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationinput
    FOR EACH ROW EXECUTE FUNCTION publishing_visual_input_insert_t022_fn();
    """,
)


SQLITE_GUARD_NAMES = (
    "pub_asset_cohort_ao_upd_t022",
    "pub_asset_cohort_ao_del_t022",
    "pub_evidence_snap_ao_upd_t022",
    "pub_evidence_snap_ao_del_t022",
    "pub_visual_snap_ao_upd_t022",
    "pub_visual_snap_ao_del_t022",
    "pub_visual_input_ao_upd_t022",
    "pub_visual_input_ao_del_t022",
    "pub_asset_cohort_insert_t022",
    "pub_evidence_snap_insert_t022",
    "pub_visual_snap_insert_t022",
    "pub_visual_input_insert_t022",
)


POSTGRES_GUARD_NAMES = (
    "pub_asset_cohort_ao_upd_t022",
    "pub_evidence_snap_ao_upd_t022",
    "pub_visual_snap_ao_upd_t022",
    "pub_visual_input_ao_upd_t022",
    "pub_asset_cohort_insert_t022",
    "pub_evidence_snap_insert_t022",
    "pub_visual_snap_insert_t022",
    "pub_visual_input_insert_t022",
)


POSTGRES_FUNCTION_NAMES = (
    "publishing_asset_append_only_t022_fn",
    "publishing_asset_cohort_insert_t022_fn",
    "publishing_evidence_snap_insert_t022_fn",
    "publishing_visual_snap_insert_t022_fn",
    "publishing_visual_input_insert_t022_fn",
)


def _hash(value):
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_asset_cohorts(apps, schema_editor):
    alias = schema_editor.connection.alias
    Revision = apps.get_model("editorial", "ArticleRevision")
    Render = apps.get_model("publishing", "ArticleChannelRender")
    Cohort = apps.get_model("publishing", "PublishedAssetCohort")

    rendered_revision_ids = set(
        Render.objects.using(alias).values_list("article_revision_id", flat=True)
    )
    for revision in Revision.objects.using(alias).filter(pk__in=rendered_revision_ids):
        renders = list(
            Render.objects.using(alias)
            .filter(article_revision_id=revision.id)
            .order_by("id")
            .values("id", "media_manifest")
        )
        has_unverifiable_material = bool(revision.visual_manifest) or any(
            row["media_manifest"] for row in renders
        )
        if has_unverifiable_material:
            manifest = [
                {
                    "legacyQuarantine": True,
                    "revisionId": str(revision.id),
                    "visualManifestHash": revision.visual_manifest_hash,
                    "renderIds": [str(row["id"]) for row in renders],
                }
            ]
            schema_version = "legacy-unverifiable-v1"
            material_state = "legacy_unverifiable"
        else:
            manifest = []
            schema_version = "published-assets-v1"
            material_state = "current"
        Cohort.objects.using(alias).create(
            revision_id=revision.id,
            schema_version=schema_version,
            material_state=material_state,
            item_count=len(manifest),
            manifest=manifest,
            manifest_hash=_hash(manifest),
        )


def install_asset_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    statements = SQLITE_GUARD_SQL if vendor == "sqlite" else POSTGRES_GUARD_SQL
    if vendor not in {"sqlite", "postgresql"}:
        raise RuntimeError(f"unsupported database vendor for T022 guards: {vendor}")
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def remove_asset_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "sqlite":
            for name in SQLITE_GUARD_NAMES:
                cursor.execute(f'DROP TRIGGER IF EXISTS "{name}"')
            return
        if vendor == "postgresql":
            for table, name in (
                ("publishing_publishedassetcohort", "pub_asset_cohort_ao_upd_t022"),
                ("publishing_publishedevidencesnapshot", "pub_evidence_snap_ao_upd_t022"),
                ("publishing_publishedvisualizationsnapshot", "pub_visual_snap_ao_upd_t022"),
                ("publishing_publishedvisualizationinput", "pub_visual_input_ao_upd_t022"),
                ("publishing_publishedassetcohort", "pub_asset_cohort_insert_t022"),
                ("publishing_publishedevidencesnapshot", "pub_evidence_snap_insert_t022"),
                ("publishing_publishedvisualizationsnapshot", "pub_visual_snap_insert_t022"),
                ("publishing_publishedvisualizationinput", "pub_visual_input_insert_t022"),
            ):
                cursor.execute(f'DROP TRIGGER IF EXISTS "{name}" ON {table}')
            for name in POSTGRES_FUNCTION_NAMES:
                cursor.execute(f'DROP FUNCTION IF EXISTS "{name}"()')
            return
        raise RuntimeError(f"unsupported database vendor for T022 guards: {vendor}")


def reject_populated_reverse(apps, schema_editor):
    for model_name in (
        "PublishedVisualizationInput",
        "PublishedVisualizationSnapshot",
        "PublishedEvidenceSnapshot",
        "PublishedAssetCohort",
    ):
        model = apps.get_model("publishing", model_name)
        if model.objects.using(schema_editor.connection.alias).exists():
            raise IrreversibleError(
                "T022 published asset lineage must be empty before reverse migration"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_editorial_policy_runtime'),
        ('evidence', '0006_generic_evidence_manifest'),
        ('publishing', '0011_publication_attempt_fencing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAssetCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema_version', models.CharField(default='published-assets-v1', max_length=40)),
                ('material_state', models.CharField(choices=[('current', '현재 정본'), ('legacy_unverifiable', '레거시 검증 불가')], default='current', max_length=24)),
                ('item_count', models.PositiveIntegerField()),
                ('manifest', models.JSONField(default=list)),
                ('manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_asset_cohort', to='editorial.articlerevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedEvidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item_id', models.UUIDField()),
                ('source_version_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('source_url_snapshot', models.URLField(max_length=1000)),
                ('source_title_snapshot', models.CharField(max_length=1000)),
                ('source_publisher_snapshot', models.CharField(max_length=300)),
                ('source_published_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('source_collected_at_snapshot', models.DateTimeField()),
                ('evidence_content_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('asset_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('object_key', models.CharField(max_length=1024)),
                ('object_version', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('locator_snapshot', models.JSONField(default=dict)),
                ('rights_status_snapshot', models.CharField(max_length=32)),
                ('rights_basis_url_snapshot', models.URLField(max_length=1000)),
                ('attribution_snapshot', models.TextField(blank=True)),
                ('alt_text_snapshot', models.TextField()),
                ('caption_snapshot', models.TextField()),
                ('presentation_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_snapshots', to='publishing.publishedassetcohort')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_asset_snapshots', to='evidence.evidenceasset')),
                ('visual_placement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_evidence_snapshot', to='editorial.visualplacement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedVisualizationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('object_key', models.CharField(max_length=1000)),
                ('object_version', models.CharField(max_length=500)),
                ('input_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('transform_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('renderer_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('mime_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('rights_status_snapshot', models.CharField(max_length=32)),
                ('rights_basis_url_snapshot', models.URLField(max_length=1000)),
                ('attribution_snapshot', models.TextField(blank=True)),
                ('alt_text_snapshot', models.TextField()),
                ('caption_snapshot', models.TextField()),
                ('presentation_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualization_snapshots', to='publishing.publishedassetcohort')),
                ('visual_placement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_visualization_snapshot', to='editorial.visualplacement')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshots', to='editorial.visualizationrender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedVisualizationInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.PositiveIntegerField()),
                ('input_material_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('evidence_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualization_input_links', to='publishing.publishedevidencesnapshot')),
                ('visualization_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_links', to='publishing.publishedvisualizationsnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visualization_snapshot', 'display_order'), name='uq_published_visualization_input_order'), models.UniqueConstraint(fields=('visualization_snapshot', 'evidence_snapshot'), name='uq_published_visualization_input_evidence')],
            },
        ),
        migrations.RunPython(backfill_asset_cohorts, migrations.RunPython.noop),
        migrations.RunPython(install_asset_guards, remove_asset_guards),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=reject_populated_reverse,
        ),
    ]
