# Generated by Django 5.2.16 on 2026-08-10 14:58

import django.core.validators
import django.db.models.deletion
import hashlib
import json
import uuid
from django.db import migrations, models
from django.db.migrations.exceptions import IrreversibleError


SQLITE_GUARD_SQL = (
    """
    CREATE TRIGGER pub_asset_cohort_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedassetcohort
    BEGIN SELECT RAISE(ABORT, 'published asset cohort is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_ao_del_t022
    BEFORE DELETE ON publishing_publishedassetcohort
    BEGIN SELECT RAISE(ABORT, 'published asset cohort is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedevidencesnapshot
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_del_t022
    BEFORE DELETE ON publishing_publishedevidencesnapshot
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedvisualizationsnapshot
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_del_t022
    BEFORE DELETE ON publishing_publishedvisualizationsnapshot
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_upd_t022
    BEFORE UPDATE ON publishing_publishedvisualizationinput
    BEGIN SELECT RAISE(ABORT, 'published visualization input is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_del_t022
    BEFORE DELETE ON publishing_publishedvisualizationinput
    BEGIN SELECT RAISE(ABORT, 'published visualization input is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_insert_t022
    BEFORE INSERT ON publishing_publishedassetcohort
    WHEN json_valid(NEW.manifest) <> 1
      OR json_type(NEW.manifest) <> 'array'
      OR json_array_length(NEW.manifest) <> NEW.item_count
    BEGIN SELECT RAISE(ABORT, 'published asset cohort manifest count mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_insert_t022
    BEFORE INSERT ON publishing_publishedevidencesnapshot
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN evidence_evidenceasset evidence
            ON evidence.id = NEW.evidence_id
          JOIN collection_sourceitem source_item
            ON source_item.id = evidence.source_item_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id = NEW.evidence_id
           AND placement.visualization_id IS NULL
           AND evidence.source_item_id = NEW.source_item_id
           AND source_item.source_version_hash = NEW.source_version_hash
    )
    BEGIN SELECT RAISE(ABORT, 'published evidence snapshot cohort revision mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_visual_snap_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationsnapshot
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN editorial_visualizationrender visualization
            ON visualization.id = NEW.visualization_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id IS NULL
           AND placement.visualization_id = NEW.visualization_id
           AND visualization.revision_id = cohort.revision_id
    )
    BEGIN SELECT RAISE(ABORT, 'published visualization snapshot cohort revision mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_visual_input_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationinput
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publishedvisualizationsnapshot visualization
          JOIN publishing_publishedevidencesnapshot evidence
            ON evidence.id = NEW.evidence_snapshot_id
         WHERE visualization.id = NEW.visualization_snapshot_id
           AND visualization.cohort_id = evidence.cohort_id
    )
    BEGIN SELECT RAISE(ABORT, 'published visualization input cohort mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_remote_media_identity_upd_t022
    BEFORE UPDATE ON publishing_remotemedia
    WHEN NEW.target_id IS NOT OLD.target_id
      OR NEW.asset_checksum IS NOT OLD.asset_checksum
      OR NEW.presentation_hash IS NOT OLD.presentation_hash
      OR NEW.remote_lookup_key IS NOT OLD.remote_lookup_key
      OR NEW.request_fingerprint IS NOT OLD.request_fingerprint
    BEGIN SELECT RAISE(ABORT, 'remote media identity is immutable'); END;
    """,
    """
    CREATE TRIGGER pub_remote_media_del_t022
    BEFORE DELETE ON publishing_remotemedia
    BEGIN SELECT RAISE(ABORT, 'remote media lineage is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_delivery_asset_identity_upd_t022
    BEFORE UPDATE ON publishing_publicdeliveryasset
    WHEN NEW.asset_checksum IS NOT OLD.asset_checksum
      OR NEW.presentation_hash IS NOT OLD.presentation_hash
      OR NEW.mime_type IS NOT OLD.mime_type
      OR NEW.byte_size IS NOT OLD.byte_size
      OR NEW.delivery_object_key IS NOT OLD.delivery_object_key
      OR NEW.rights_status_snapshot IS NOT OLD.rights_status_snapshot
      OR NEW.alt_text_snapshot IS NOT OLD.alt_text_snapshot
      OR NEW.caption_snapshot IS NOT OLD.caption_snapshot
      OR NEW.attribution_snapshot IS NOT OLD.attribution_snapshot
      OR NEW.created_at IS NOT OLD.created_at
    BEGIN SELECT RAISE(ABORT, 'public delivery asset identity is immutable'); END;
    """,
    """
    CREATE TRIGGER pub_delivery_asset_del_t022
    BEFORE DELETE ON publishing_publicdeliveryasset
    BEGIN SELECT RAISE(ABORT, 'public delivery asset lineage is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_media_binding_identity_upd_t022
    BEFORE UPDATE ON publishing_publicationmedia
    WHEN NEW.publication_id IS NOT OLD.publication_id
      OR NEW.remote_media_id IS NOT OLD.remote_media_id
      OR NEW.public_delivery_asset_id IS NOT OLD.public_delivery_asset_id
      OR NEW.article_revision_id IS NOT OLD.article_revision_id
      OR NEW.asset_cohort_id IS NOT OLD.asset_cohort_id
      OR NEW.published_evidence_snapshot_id IS NOT OLD.published_evidence_snapshot_id
      OR NEW.published_visualization_snapshot_id IS NOT OLD.published_visualization_snapshot_id
      OR NEW.usage IS NOT OLD.usage
      OR NEW.block_id IS NOT OLD.block_id
      OR NEW.display_order IS NOT OLD.display_order
      OR NEW.alt_text_snapshot IS NOT OLD.alt_text_snapshot
      OR NEW.caption_snapshot IS NOT OLD.caption_snapshot
      OR NEW.attribution_snapshot IS NOT OLD.attribution_snapshot
      OR NEW.created_at IS NOT OLD.created_at
    BEGIN SELECT RAISE(ABORT, 'publication media binding identity is immutable'); END;
    """,
    """
    CREATE TRIGGER pub_media_binding_del_t022
    BEFORE DELETE ON publishing_publicationmedia
    BEGIN SELECT RAISE(ABORT, 'publication media binding is append-only'); END;
    """,
    """
    CREATE TRIGGER pub_media_binding_insert_t022
    BEFORE INSERT ON publishing_publicationmedia
    WHEN NOT EXISTS (
        SELECT 1
          FROM publishing_publication publication
          JOIN editorial_articlerevision revision
            ON revision.id = NEW.article_revision_id
          JOIN publishing_publishedassetcohort cohort
            ON cohort.id = NEW.asset_cohort_id
         WHERE publication.id = NEW.publication_id
           AND publication.article_id = revision.article_id
           AND cohort.revision_id = revision.id
           AND (
             (
               NEW.published_evidence_snapshot_id IS NOT NULL
               AND NEW.published_visualization_snapshot_id IS NULL
               AND EXISTS (
                 SELECT 1
                   FROM publishing_publishedevidencesnapshot snapshot
                  WHERE snapshot.id = NEW.published_evidence_snapshot_id
                    AND snapshot.cohort_id = cohort.id
                    AND (
                      (NEW.remote_media_id IS NOT NULL
                       AND NEW.public_delivery_asset_id IS NULL
                       AND EXISTS (
                         SELECT 1 FROM publishing_remotemedia mapping
                          WHERE mapping.id = NEW.remote_media_id
                            AND mapping.target_id = publication.target_id
                            AND mapping.asset_checksum = snapshot.asset_checksum
                            AND mapping.presentation_hash = snapshot.presentation_hash
                       ))
                      OR
                      (NEW.remote_media_id IS NULL
                       AND NEW.public_delivery_asset_id IS NOT NULL
                       AND EXISTS (
                         SELECT 1 FROM publishing_publicdeliveryasset mapping
                          WHERE mapping.id = NEW.public_delivery_asset_id
                            AND mapping.asset_checksum = snapshot.asset_checksum
                            AND mapping.presentation_hash = snapshot.presentation_hash
                       ))
                    )
               )
             )
             OR
             (
               NEW.published_evidence_snapshot_id IS NULL
               AND NEW.published_visualization_snapshot_id IS NOT NULL
               AND EXISTS (
                 SELECT 1
                   FROM publishing_publishedvisualizationsnapshot snapshot
                  WHERE snapshot.id = NEW.published_visualization_snapshot_id
                    AND snapshot.cohort_id = cohort.id
                    AND (
                      (NEW.remote_media_id IS NOT NULL
                       AND NEW.public_delivery_asset_id IS NULL
                       AND EXISTS (
                         SELECT 1 FROM publishing_remotemedia mapping
                          WHERE mapping.id = NEW.remote_media_id
                            AND mapping.target_id = publication.target_id
                            AND mapping.asset_checksum = snapshot.output_checksum
                            AND mapping.presentation_hash = snapshot.presentation_hash
                       ))
                      OR
                      (NEW.remote_media_id IS NULL
                       AND NEW.public_delivery_asset_id IS NOT NULL
                       AND EXISTS (
                         SELECT 1 FROM publishing_publicdeliveryasset mapping
                          WHERE mapping.id = NEW.public_delivery_asset_id
                            AND mapping.asset_checksum = snapshot.output_checksum
                            AND mapping.presentation_hash = snapshot.presentation_hash
                       ))
                    )
               )
             )
           )
    )
    BEGIN SELECT RAISE(ABORT, 'publication media binding lineage mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_media_operation_insert_t022
    BEFORE INSERT ON publishing_mediadeliveryoperation
    WHEN NOT EXISTS (
        SELECT 1
          FROM infrastructure_outboxmessage event
         WHERE event.id = NEW.source_event_id
           AND event.event_version = 2
           AND event.aggregate_type = NEW.mapping_kind
           AND event.aggregate_id = COALESCE(NEW.remote_media_id, NEW.public_delivery_asset_id)
           AND event.topic = CASE
             WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'upload'
               THEN 'media.upload_requested'
             WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'reconcile'
               THEN 'media.reconcile_requested'
             WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'delete'
               THEN 'media.delete_requested'
             WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'prepare'
               THEN 'delivery.prepare_requested'
             WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'reconcile'
               THEN 'delivery.reconcile_requested'
             WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'delete'
               THEN 'delivery.delete_requested'
             ELSE ''
           END
           AND CAST(json_extract(event.payload, '$.operation_generation') AS INTEGER) = NEW.generation
           AND replace(
                 COALESCE(
                   json_extract(event.payload, '$.remote_media_id'),
                   json_extract(event.payload, '$.public_delivery_asset_id')
                 ),
                 '-',
                 ''
               ) = COALESCE(NEW.remote_media_id, NEW.public_delivery_asset_id)
           AND (
             (NEW.action = 'delete'
              AND NEW.publication_attempt_id IS NULL
              AND NEW.publication_intent_id IS NULL
              AND NEW.target_snapshot_id IS NULL
              AND NEW.target_config_hash = '')
             OR
             (NEW.action <> 'delete'
              AND NEW.publication_attempt_id IS NOT NULL
              AND NEW.publication_intent_id IS NOT NULL
              AND replace(json_extract(event.payload, '$.publication_attempt_id'), '-', '') = NEW.publication_attempt_id
              AND replace(json_extract(event.payload, '$.publication_intent_id'), '-', '') = NEW.publication_intent_id
              AND EXISTS (
                SELECT 1
                  FROM publishing_publicationattempt attempt
                 WHERE attempt.id = NEW.publication_attempt_id
                   AND attempt.publication_intent_id = NEW.publication_intent_id
                   AND (
                     (NEW.action = 'upload'
                      AND attempt.target_snapshot_id = NEW.target_snapshot_id
                      AND attempt.target_config_hash = NEW.target_config_hash
                      AND replace(json_extract(event.payload, '$.target_snapshot_id'), '-', '') = NEW.target_snapshot_id
                      AND json_extract(event.payload, '$.target_config_hash') = NEW.target_config_hash)
                     OR
                     (NEW.action <> 'upload'
                      AND NEW.target_snapshot_id IS NULL
                      AND NEW.target_config_hash = '')
                   )
              ))
           )
           AND NEW.generation = COALESCE(
             (
               SELECT MAX(prior.generation) + 1
                 FROM publishing_mediadeliveryoperation prior
                WHERE prior.remote_media_id IS NEW.remote_media_id
                  AND prior.public_delivery_asset_id IS NEW.public_delivery_asset_id
             ),
             1
           )
    )
    BEGIN SELECT RAISE(ABORT, 'media delivery operation event lineage mismatch'); END;
    """,
    """
    CREATE TRIGGER pub_media_operation_identity_upd_t022
    BEFORE UPDATE ON publishing_mediadeliveryoperation
    WHEN NEW.mapping_kind IS NOT OLD.mapping_kind
      OR NEW.remote_media_id IS NOT OLD.remote_media_id
      OR NEW.public_delivery_asset_id IS NOT OLD.public_delivery_asset_id
      OR NEW.publication_attempt_id IS NOT OLD.publication_attempt_id
      OR NEW.publication_intent_id IS NOT OLD.publication_intent_id
      OR NEW.action IS NOT OLD.action
      OR NEW.generation IS NOT OLD.generation
      OR NEW.source_event_id IS NOT OLD.source_event_id
      OR NEW.target_snapshot_id IS NOT OLD.target_snapshot_id
      OR NEW.target_config_hash IS NOT OLD.target_config_hash
      OR NEW.material_hash IS NOT OLD.material_hash
      OR NEW.created_at IS NOT OLD.created_at
    BEGIN SELECT RAISE(ABORT, 'media delivery operation identity is immutable'); END;
    """,
    """
    CREATE TRIGGER pub_media_operation_state_upd_t022
    BEFORE UPDATE ON publishing_mediadeliveryoperation
    WHEN NOT (
      (NEW.state = OLD.state)
      OR (OLD.state = 'queued' AND NEW.state IN ('running', 'delivery_failed', 'superseded'))
      OR (OLD.state = 'running' AND NEW.state IN ('succeeded', 'unknown_outcome', 'manual_required', 'delivery_failed', 'superseded'))
    )
    OR (
      NEW.state = 'running'
      AND NOT EXISTS (
        SELECT 1
          FROM infrastructure_outboxconsumerreceipt receipt
         WHERE receipt.event_id = NEW.source_event_id
           AND receipt.consumer_name = NEW.consumer_name
           AND receipt.state = 'processing'
           AND receipt.lease_generation = NEW.consumer_lease_generation
           AND receipt.lease_token = NEW.consumer_lease_token
           AND julianday(receipt.claimed_until) > julianday('now')
           AND NEW.lease_token_hash <> ''
           AND NEW.lease_expires_at = receipt.claimed_until
      )
    )
    OR (
      (NEW.write_marker = '') IS NOT (NEW.external_write_started_at IS NULL)
    )
    OR (
      NEW.write_marker IS NOT OLD.write_marker
      AND NOT (
        OLD.write_marker = ''
        AND OLD.external_write_started_at IS NULL
        AND NEW.state = 'running'
        AND length(NEW.write_marker) = 64
        AND NEW.write_marker NOT GLOB '*[^0-9a-f]*'
        AND NEW.external_write_started_at IS NOT NULL
        AND EXISTS (
          SELECT 1
            FROM infrastructure_outboxconsumerreceipt receipt
           WHERE receipt.event_id = NEW.source_event_id
             AND receipt.consumer_name = NEW.consumer_name
             AND receipt.state = 'processing'
             AND receipt.lease_generation = NEW.consumer_lease_generation
             AND receipt.lease_token = NEW.consumer_lease_token
             AND julianday(receipt.claimed_until) > julianday('now')
        )
      )
    )
    OR (
      OLD.state IN ('succeeded', 'unknown_outcome', 'manual_required', 'delivery_failed', 'superseded')
      AND (
        NEW.state IS NOT OLD.state
        OR NEW.consumer_name IS NOT OLD.consumer_name
        OR NEW.consumer_lease_generation IS NOT OLD.consumer_lease_generation
        OR NEW.consumer_lease_token IS NOT OLD.consumer_lease_token
        OR NEW.lease_token_hash IS NOT OLD.lease_token_hash
        OR NEW.lease_expires_at IS NOT OLD.lease_expires_at
        OR NEW.write_marker IS NOT OLD.write_marker
        OR NEW.external_write_started_at IS NOT OLD.external_write_started_at
        OR NEW.result_hash IS NOT OLD.result_hash
        OR NEW.error_code IS NOT OLD.error_code
        OR NEW.started_at IS NOT OLD.started_at
        OR NEW.finished_at IS NOT OLD.finished_at
      )
    )
    BEGIN SELECT RAISE(ABORT, 'media delivery operation state transition is invalid'); END;
    """,
    """
    CREATE TRIGGER pub_media_operation_del_t022
    BEFORE DELETE ON publishing_mediadeliveryoperation
    BEGIN SELECT RAISE(ABORT, 'media delivery operation is append-only'); END;
    """,
)


POSTGRES_GUARD_SQL = (
    """
    CREATE OR REPLACE FUNCTION publishing_asset_append_only_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'published asset snapshot is append-only';
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedassetcohort
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_evidence_snap_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedevidencesnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_visual_snap_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedvisualizationsnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE TRIGGER pub_visual_input_ao_upd_t022
    BEFORE UPDATE OR DELETE ON publishing_publishedvisualizationinput
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_append_only_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_asset_cohort_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF jsonb_typeof(NEW.manifest) IS DISTINCT FROM 'array'
         OR jsonb_array_length(NEW.manifest) IS DISTINCT FROM NEW.item_count THEN
        RAISE EXCEPTION 'published asset cohort manifest count mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_asset_cohort_insert_t022
    BEFORE INSERT ON publishing_publishedassetcohort
    FOR EACH ROW EXECUTE FUNCTION publishing_asset_cohort_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_evidence_snap_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN evidence_evidenceasset evidence
            ON evidence.id = NEW.evidence_id
          JOIN collection_sourceitem source_item
            ON source_item.id = evidence.source_item_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id = NEW.evidence_id
           AND placement.visualization_id IS NULL
           AND evidence.source_item_id = NEW.source_item_id
           AND source_item.source_version_hash = NEW.source_version_hash
      ) THEN
        RAISE EXCEPTION 'published evidence snapshot cohort revision mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_evidence_snap_insert_t022
    BEFORE INSERT ON publishing_publishedevidencesnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_evidence_snap_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_visual_snap_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedassetcohort cohort
          JOIN editorial_visualplacement placement
            ON placement.id = NEW.visual_placement_id
          JOIN editorial_visualizationrender visualization
            ON visualization.id = NEW.visualization_id
         WHERE cohort.id = NEW.cohort_id
           AND cohort.revision_id = placement.revision_id
           AND placement.source_evidence_id IS NULL
           AND placement.visualization_id = NEW.visualization_id
           AND visualization.revision_id = cohort.revision_id
      ) THEN
        RAISE EXCEPTION 'published visualization snapshot cohort revision mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_visual_snap_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationsnapshot
    FOR EACH ROW EXECUTE FUNCTION publishing_visual_snap_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_visual_input_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publishedvisualizationsnapshot visualization
          JOIN publishing_publishedevidencesnapshot evidence
            ON evidence.id = NEW.evidence_snapshot_id
         WHERE visualization.id = NEW.visualization_snapshot_id
           AND visualization.cohort_id = evidence.cohort_id
      ) THEN
        RAISE EXCEPTION 'published visualization input cohort mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_visual_input_insert_t022
    BEFORE INSERT ON publishing_publishedvisualizationinput
    FOR EACH ROW EXECUTE FUNCTION publishing_visual_input_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_remote_media_guard_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'remote media lineage is append-only';
      END IF;
      IF NEW.target_id IS DISTINCT FROM OLD.target_id
         OR NEW.asset_checksum IS DISTINCT FROM OLD.asset_checksum
         OR NEW.presentation_hash IS DISTINCT FROM OLD.presentation_hash
         OR NEW.remote_lookup_key IS DISTINCT FROM OLD.remote_lookup_key
         OR NEW.request_fingerprint IS DISTINCT FROM OLD.request_fingerprint THEN
        RAISE EXCEPTION 'remote media identity is immutable';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_remote_media_guard_t022
    BEFORE UPDATE OR DELETE ON publishing_remotemedia
    FOR EACH ROW EXECUTE FUNCTION publishing_remote_media_guard_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_delivery_asset_guard_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'public delivery asset lineage is append-only';
      END IF;
      IF NEW.asset_checksum IS DISTINCT FROM OLD.asset_checksum
         OR NEW.presentation_hash IS DISTINCT FROM OLD.presentation_hash
         OR NEW.mime_type IS DISTINCT FROM OLD.mime_type
         OR NEW.byte_size IS DISTINCT FROM OLD.byte_size
         OR NEW.delivery_object_key IS DISTINCT FROM OLD.delivery_object_key
         OR NEW.rights_status_snapshot IS DISTINCT FROM OLD.rights_status_snapshot
         OR NEW.alt_text_snapshot IS DISTINCT FROM OLD.alt_text_snapshot
         OR NEW.caption_snapshot IS DISTINCT FROM OLD.caption_snapshot
         OR NEW.attribution_snapshot IS DISTINCT FROM OLD.attribution_snapshot
         OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'public delivery asset identity is immutable';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_delivery_asset_guard_t022
    BEFORE UPDATE OR DELETE ON publishing_publicdeliveryasset
    FOR EACH ROW EXECUTE FUNCTION publishing_delivery_asset_guard_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_media_binding_guard_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'publication media binding is append-only';
      END IF;
      IF NEW.publication_id IS DISTINCT FROM OLD.publication_id
         OR NEW.remote_media_id IS DISTINCT FROM OLD.remote_media_id
         OR NEW.public_delivery_asset_id IS DISTINCT FROM OLD.public_delivery_asset_id
         OR NEW.article_revision_id IS DISTINCT FROM OLD.article_revision_id
         OR NEW.asset_cohort_id IS DISTINCT FROM OLD.asset_cohort_id
         OR NEW.published_evidence_snapshot_id IS DISTINCT FROM OLD.published_evidence_snapshot_id
         OR NEW.published_visualization_snapshot_id IS DISTINCT FROM OLD.published_visualization_snapshot_id
         OR NEW.usage IS DISTINCT FROM OLD.usage
         OR NEW.block_id IS DISTINCT FROM OLD.block_id
         OR NEW.display_order IS DISTINCT FROM OLD.display_order
         OR NEW.alt_text_snapshot IS DISTINCT FROM OLD.alt_text_snapshot
         OR NEW.caption_snapshot IS DISTINCT FROM OLD.caption_snapshot
         OR NEW.attribution_snapshot IS DISTINCT FROM OLD.attribution_snapshot
         OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'publication media binding identity is immutable';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_media_binding_guard_t022
    BEFORE UPDATE OR DELETE ON publishing_publicationmedia
    FOR EACH ROW EXECUTE FUNCTION publishing_media_binding_guard_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_media_binding_insert_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1
          FROM publishing_publication publication
          JOIN editorial_articlerevision revision
            ON revision.id = NEW.article_revision_id
          JOIN publishing_publishedassetcohort cohort
            ON cohort.id = NEW.asset_cohort_id
         WHERE publication.id = NEW.publication_id
           AND publication.article_id = revision.article_id
           AND cohort.revision_id = revision.id
           AND (
             (NEW.published_evidence_snapshot_id IS NOT NULL
              AND NEW.published_visualization_snapshot_id IS NULL
              AND EXISTS (
                SELECT 1 FROM publishing_publishedevidencesnapshot snapshot
                 WHERE snapshot.id = NEW.published_evidence_snapshot_id
                   AND snapshot.cohort_id = cohort.id
                   AND (
                     (NEW.remote_media_id IS NOT NULL
                      AND NEW.public_delivery_asset_id IS NULL
                      AND EXISTS (
                        SELECT 1 FROM publishing_remotemedia mapping
                         WHERE mapping.id = NEW.remote_media_id
                           AND mapping.target_id = publication.target_id
                           AND mapping.asset_checksum = snapshot.asset_checksum
                           AND mapping.presentation_hash = snapshot.presentation_hash))
                     OR
                     (NEW.remote_media_id IS NULL
                      AND NEW.public_delivery_asset_id IS NOT NULL
                      AND EXISTS (
                        SELECT 1 FROM publishing_publicdeliveryasset mapping
                         WHERE mapping.id = NEW.public_delivery_asset_id
                           AND mapping.asset_checksum = snapshot.asset_checksum
                           AND mapping.presentation_hash = snapshot.presentation_hash))
                   )))
             OR
             (NEW.published_evidence_snapshot_id IS NULL
              AND NEW.published_visualization_snapshot_id IS NOT NULL
              AND EXISTS (
                SELECT 1 FROM publishing_publishedvisualizationsnapshot snapshot
                 WHERE snapshot.id = NEW.published_visualization_snapshot_id
                   AND snapshot.cohort_id = cohort.id
                   AND (
                     (NEW.remote_media_id IS NOT NULL
                      AND NEW.public_delivery_asset_id IS NULL
                      AND EXISTS (
                        SELECT 1 FROM publishing_remotemedia mapping
                         WHERE mapping.id = NEW.remote_media_id
                           AND mapping.target_id = publication.target_id
                           AND mapping.asset_checksum = snapshot.output_checksum
                           AND mapping.presentation_hash = snapshot.presentation_hash))
                     OR
                     (NEW.remote_media_id IS NULL
                      AND NEW.public_delivery_asset_id IS NOT NULL
                      AND EXISTS (
                        SELECT 1 FROM publishing_publicdeliveryasset mapping
                         WHERE mapping.id = NEW.public_delivery_asset_id
                           AND mapping.asset_checksum = snapshot.output_checksum
                           AND mapping.presentation_hash = snapshot.presentation_hash))
                   )))
           )
      ) THEN
        RAISE EXCEPTION 'publication media binding lineage mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_media_binding_insert_t022
    BEFORE INSERT ON publishing_publicationmedia
    FOR EACH ROW EXECUTE FUNCTION publishing_media_binding_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_media_operation_insert_t022_fn()
    RETURNS trigger AS $$
    DECLARE
      expected_topic text;
      mapping_id uuid;
      prior_generation integer;
    BEGIN
      mapping_id := COALESCE(NEW.remote_media_id, NEW.public_delivery_asset_id);
      expected_topic := CASE
        WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'upload' THEN 'media.upload_requested'
        WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'reconcile' THEN 'media.reconcile_requested'
        WHEN NEW.mapping_kind = 'remote_media' AND NEW.action = 'delete' THEN 'media.delete_requested'
        WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'prepare' THEN 'delivery.prepare_requested'
        WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'reconcile' THEN 'delivery.reconcile_requested'
        WHEN NEW.mapping_kind = 'public_delivery_asset' AND NEW.action = 'delete' THEN 'delivery.delete_requested'
        ELSE ''
      END;
      SELECT MAX(prior.generation)
        INTO prior_generation
        FROM publishing_mediadeliveryoperation prior
       WHERE prior.remote_media_id IS NOT DISTINCT FROM NEW.remote_media_id
         AND prior.public_delivery_asset_id IS NOT DISTINCT FROM NEW.public_delivery_asset_id;
      IF NEW.generation IS DISTINCT FROM COALESCE(prior_generation + 1, 1)
         OR NOT EXISTS (
           SELECT 1
             FROM infrastructure_outboxmessage event
            WHERE event.id = NEW.source_event_id
              AND event.event_version = 2
              AND event.aggregate_type = NEW.mapping_kind
              AND event.aggregate_id = mapping_id
              AND event.topic = expected_topic
              AND (event.payload ->> 'operation_generation')::integer = NEW.generation
              AND COALESCE(
                    event.payload ->> 'remote_media_id',
                    event.payload ->> 'public_delivery_asset_id'
                  )::uuid = mapping_id
              AND (
                (NEW.action = 'delete'
                 AND NEW.publication_attempt_id IS NULL
                 AND NEW.publication_intent_id IS NULL
                 AND NEW.target_snapshot_id IS NULL
                 AND NEW.target_config_hash = '')
                OR
                (NEW.action <> 'delete'
                 AND NEW.publication_attempt_id IS NOT NULL
                 AND NEW.publication_intent_id IS NOT NULL
                 AND (event.payload ->> 'publication_attempt_id')::uuid = NEW.publication_attempt_id
                 AND (event.payload ->> 'publication_intent_id')::uuid = NEW.publication_intent_id
                 AND EXISTS (
                   SELECT 1
                     FROM publishing_publicationattempt attempt
                    WHERE attempt.id = NEW.publication_attempt_id
                      AND attempt.publication_intent_id = NEW.publication_intent_id
                      AND (
                        (NEW.action = 'upload'
                         AND attempt.target_snapshot_id = NEW.target_snapshot_id
                         AND attempt.target_config_hash = NEW.target_config_hash
                         AND (event.payload ->> 'target_snapshot_id')::uuid = NEW.target_snapshot_id
                         AND event.payload ->> 'target_config_hash' = NEW.target_config_hash)
                        OR
                        (NEW.action <> 'upload'
                         AND NEW.target_snapshot_id IS NULL
                         AND NEW.target_config_hash = '')
                      )
                 ))
              )
         ) THEN
        RAISE EXCEPTION 'media delivery operation event lineage mismatch';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_media_operation_insert_t022
    BEFORE INSERT ON publishing_mediadeliveryoperation
    FOR EACH ROW EXECUTE FUNCTION publishing_media_operation_insert_t022_fn();
    """,
    """
    CREATE OR REPLACE FUNCTION publishing_media_operation_guard_t022_fn()
    RETURNS trigger AS $$
    BEGIN
      IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'media delivery operation is append-only';
      END IF;
      IF NEW.mapping_kind IS DISTINCT FROM OLD.mapping_kind
         OR NEW.remote_media_id IS DISTINCT FROM OLD.remote_media_id
         OR NEW.public_delivery_asset_id IS DISTINCT FROM OLD.public_delivery_asset_id
         OR NEW.publication_attempt_id IS DISTINCT FROM OLD.publication_attempt_id
         OR NEW.publication_intent_id IS DISTINCT FROM OLD.publication_intent_id
         OR NEW.action IS DISTINCT FROM OLD.action
         OR NEW.generation IS DISTINCT FROM OLD.generation
         OR NEW.source_event_id IS DISTINCT FROM OLD.source_event_id
         OR NEW.target_snapshot_id IS DISTINCT FROM OLD.target_snapshot_id
         OR NEW.target_config_hash IS DISTINCT FROM OLD.target_config_hash
         OR NEW.material_hash IS DISTINCT FROM OLD.material_hash
         OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'media delivery operation identity is immutable';
      END IF;
      IF NOT (
        NEW.state = OLD.state
        OR (OLD.state = 'queued' AND NEW.state IN ('running', 'delivery_failed', 'superseded'))
        OR (OLD.state = 'running' AND NEW.state IN ('succeeded', 'unknown_outcome', 'manual_required', 'delivery_failed', 'superseded'))
      ) THEN
        RAISE EXCEPTION 'media delivery operation state transition is invalid';
      END IF;
      IF NEW.state = 'running' AND NOT EXISTS (
        SELECT 1
          FROM infrastructure_outboxconsumerreceipt receipt
         WHERE receipt.event_id = NEW.source_event_id
           AND receipt.consumer_name = NEW.consumer_name
           AND receipt.state = 'processing'
           AND receipt.lease_generation = NEW.consumer_lease_generation
           AND receipt.lease_token = NEW.consumer_lease_token
           AND receipt.claimed_until > clock_timestamp()
           AND NEW.lease_token_hash <> ''
           AND NEW.lease_expires_at = receipt.claimed_until
      ) THEN
        RAISE EXCEPTION 'media delivery operation receipt capability mismatch';
      END IF;
      IF (NEW.write_marker = '') IS DISTINCT FROM (NEW.external_write_started_at IS NULL) THEN
        RAISE EXCEPTION 'media delivery operation write marker is incomplete';
      END IF;
      IF NEW.write_marker IS DISTINCT FROM OLD.write_marker
         AND NOT (
           OLD.write_marker = ''
           AND OLD.external_write_started_at IS NULL
           AND NEW.state = 'running'
           AND NEW.write_marker ~ '^[0-9a-f]{64}$'
           AND NEW.external_write_started_at IS NOT NULL
           AND EXISTS (
             SELECT 1
               FROM infrastructure_outboxconsumerreceipt receipt
              WHERE receipt.event_id = NEW.source_event_id
                AND receipt.consumer_name = NEW.consumer_name
                AND receipt.state = 'processing'
                AND receipt.lease_generation = NEW.consumer_lease_generation
                AND receipt.lease_token = NEW.consumer_lease_token
                AND receipt.claimed_until > clock_timestamp()
           )
         ) THEN
        RAISE EXCEPTION 'media delivery operation write marker is immutable';
      END IF;
      IF OLD.state IN ('succeeded', 'unknown_outcome', 'manual_required', 'delivery_failed', 'superseded')
         AND (
           NEW.state IS DISTINCT FROM OLD.state
           OR NEW.consumer_name IS DISTINCT FROM OLD.consumer_name
           OR NEW.consumer_lease_generation IS DISTINCT FROM OLD.consumer_lease_generation
           OR NEW.consumer_lease_token IS DISTINCT FROM OLD.consumer_lease_token
           OR NEW.lease_token_hash IS DISTINCT FROM OLD.lease_token_hash
           OR NEW.lease_expires_at IS DISTINCT FROM OLD.lease_expires_at
           OR NEW.write_marker IS DISTINCT FROM OLD.write_marker
           OR NEW.external_write_started_at IS DISTINCT FROM OLD.external_write_started_at
           OR NEW.result_hash IS DISTINCT FROM OLD.result_hash
           OR NEW.error_code IS DISTINCT FROM OLD.error_code
           OR NEW.started_at IS DISTINCT FROM OLD.started_at
           OR NEW.finished_at IS DISTINCT FROM OLD.finished_at
         ) THEN
        RAISE EXCEPTION 'media delivery operation terminal state is immutable';
      END IF;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """,
    """
    CREATE TRIGGER pub_media_operation_guard_t022
    BEFORE UPDATE OR DELETE ON publishing_mediadeliveryoperation
    FOR EACH ROW EXECUTE FUNCTION publishing_media_operation_guard_t022_fn();
    """,
)


SQLITE_GUARD_NAMES = (
    "pub_asset_cohort_ao_upd_t022",
    "pub_asset_cohort_ao_del_t022",
    "pub_evidence_snap_ao_upd_t022",
    "pub_evidence_snap_ao_del_t022",
    "pub_visual_snap_ao_upd_t022",
    "pub_visual_snap_ao_del_t022",
    "pub_visual_input_ao_upd_t022",
    "pub_visual_input_ao_del_t022",
    "pub_asset_cohort_insert_t022",
    "pub_evidence_snap_insert_t022",
    "pub_visual_snap_insert_t022",
    "pub_visual_input_insert_t022",
    "pub_remote_media_identity_upd_t022",
    "pub_remote_media_del_t022",
    "pub_delivery_asset_identity_upd_t022",
    "pub_delivery_asset_del_t022",
    "pub_media_binding_identity_upd_t022",
    "pub_media_binding_del_t022",
    "pub_media_binding_insert_t022",
    "pub_media_operation_insert_t022",
    "pub_media_operation_identity_upd_t022",
    "pub_media_operation_state_upd_t022",
    "pub_media_operation_del_t022",
)


POSTGRES_GUARD_NAMES = (
    "pub_asset_cohort_ao_upd_t022",
    "pub_evidence_snap_ao_upd_t022",
    "pub_visual_snap_ao_upd_t022",
    "pub_visual_input_ao_upd_t022",
    "pub_asset_cohort_insert_t022",
    "pub_evidence_snap_insert_t022",
    "pub_visual_snap_insert_t022",
    "pub_visual_input_insert_t022",
    "pub_remote_media_guard_t022",
    "pub_delivery_asset_guard_t022",
    "pub_media_binding_guard_t022",
    "pub_media_binding_insert_t022",
    "pub_media_operation_insert_t022",
    "pub_media_operation_guard_t022",
)


POSTGRES_FUNCTION_NAMES = (
    "publishing_asset_append_only_t022_fn",
    "publishing_asset_cohort_insert_t022_fn",
    "publishing_evidence_snap_insert_t022_fn",
    "publishing_visual_snap_insert_t022_fn",
    "publishing_visual_input_insert_t022_fn",
    "publishing_remote_media_guard_t022_fn",
    "publishing_delivery_asset_guard_t022_fn",
    "publishing_media_binding_guard_t022_fn",
    "publishing_media_binding_insert_t022_fn",
    "publishing_media_operation_insert_t022_fn",
    "publishing_media_operation_guard_t022_fn",
)


def _hash(value):
    encoded = json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def backfill_asset_cohorts(apps, schema_editor):
    alias = schema_editor.connection.alias
    Revision = apps.get_model("editorial", "ArticleRevision")
    Render = apps.get_model("publishing", "ArticleChannelRender")
    Cohort = apps.get_model("publishing", "PublishedAssetCohort")

    rendered_revision_ids = set(
        Render.objects.using(alias).values_list("article_revision_id", flat=True)
    )
    for revision in Revision.objects.using(alias).filter(pk__in=rendered_revision_ids):
        renders = list(
            Render.objects.using(alias)
            .filter(article_revision_id=revision.id)
            .order_by("id")
            .values("id", "media_manifest")
        )
        has_unverifiable_material = bool(revision.visual_manifest) or any(
            row["media_manifest"] for row in renders
        )
        if has_unverifiable_material:
            manifest = [
                {
                    "legacyQuarantine": True,
                    "revisionId": str(revision.id),
                    "visualManifestHash": revision.visual_manifest_hash,
                    "renderIds": [str(row["id"]) for row in renders],
                }
            ]
            schema_version = "legacy-unverifiable-v1"
            material_state = "legacy_unverifiable"
        else:
            manifest = []
            schema_version = "published-assets-v1"
            material_state = "current"
        Cohort.objects.using(alias).create(
            revision_id=revision.id,
            schema_version=schema_version,
            material_state=material_state,
            item_count=len(manifest),
            manifest=manifest,
            manifest_hash=_hash(manifest),
        )


def bind_existing_publication_media(apps, schema_editor):
    alias = schema_editor.connection.alias
    PublicationMedia = apps.get_model("publishing", "PublicationMedia")
    EvidenceSnapshot = apps.get_model("publishing", "PublishedEvidenceSnapshot")
    VisualizationSnapshot = apps.get_model(
        "publishing", "PublishedVisualizationSnapshot"
    )

    for binding in PublicationMedia.objects.using(alias).order_by("id"):
        evidence_snapshot_id = binding.published_evidence_snapshot_id
        visualization_snapshot_id = binding.published_visualization_snapshot_id
        if bool(evidence_snapshot_id) == bool(visualization_snapshot_id):
            raise RuntimeError(
                f"publication media {binding.id} has ambiguous frozen provenance"
            )

        if evidence_snapshot_id:
            snapshot = (
                EvidenceSnapshot.objects.using(alias)
                .select_related("cohort")
                .filter(pk=evidence_snapshot_id)
                .first()
            )
            if snapshot is None:
                raise RuntimeError(
                    f"publication media {binding.id} evidence snapshot is unverifiable"
                )
            if binding.evidence_asset_id not in (None, snapshot.evidence_id):
                raise RuntimeError(
                    f"publication media {binding.id} evidence identity mismatch"
                )
            asset_checksum = snapshot.asset_checksum
            presentation_hash = snapshot.presentation_hash
        else:
            snapshot = (
                VisualizationSnapshot.objects.using(alias)
                .select_related("cohort")
                .filter(pk=visualization_snapshot_id)
                .first()
            )
            if snapshot is None:
                raise RuntimeError(
                    f"publication media {binding.id} visualization snapshot is unverifiable"
                )
            if binding.evidence_asset_id is not None:
                raise RuntimeError(
                    f"publication media {binding.id} has contradictory evidence identity"
                )
            asset_checksum = snapshot.output_checksum
            presentation_hash = snapshot.presentation_hash

        if snapshot.cohort.revision_id != binding.article_revision_id:
            raise RuntimeError(
                f"publication media {binding.id} revision/cohort mismatch"
            )
        if binding.remote_media_id:
            remote = binding.remote_media
            if (
                remote.asset_checksum != asset_checksum
                or remote.presentation_hash != presentation_hash
            ):
                raise RuntimeError(
                    f"publication media {binding.id} remote material mismatch"
                )
        else:
            delivery = binding.public_delivery_asset
            if (
                delivery.asset_checksum != asset_checksum
                or delivery.presentation_hash != presentation_hash
            ):
                raise RuntimeError(
                    f"publication media {binding.id} delivery material mismatch"
                )

        update_fields = {"asset_cohort_id": snapshot.cohort_id}
        if evidence_snapshot_id:
            update_fields["evidence_snapshot_ref_id"] = snapshot.id
        else:
            update_fields["visualization_snapshot_ref_id"] = snapshot.id
        PublicationMedia.objects.using(alias).filter(pk=binding.id).update(
            **update_fields
        )


def install_asset_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    statements = SQLITE_GUARD_SQL if vendor == "sqlite" else POSTGRES_GUARD_SQL
    if vendor not in {"sqlite", "postgresql"}:
        raise RuntimeError(f"unsupported database vendor for T022 guards: {vendor}")
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)


def remove_asset_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == "sqlite":
            for name in SQLITE_GUARD_NAMES:
                cursor.execute(f'DROP TRIGGER IF EXISTS "{name}"')
            return
        if vendor == "postgresql":
            for table, name in (
                ("publishing_publishedassetcohort", "pub_asset_cohort_ao_upd_t022"),
                ("publishing_publishedevidencesnapshot", "pub_evidence_snap_ao_upd_t022"),
                ("publishing_publishedvisualizationsnapshot", "pub_visual_snap_ao_upd_t022"),
                ("publishing_publishedvisualizationinput", "pub_visual_input_ao_upd_t022"),
                ("publishing_publishedassetcohort", "pub_asset_cohort_insert_t022"),
                ("publishing_publishedevidencesnapshot", "pub_evidence_snap_insert_t022"),
                ("publishing_publishedvisualizationsnapshot", "pub_visual_snap_insert_t022"),
                ("publishing_publishedvisualizationinput", "pub_visual_input_insert_t022"),
                ("publishing_remotemedia", "pub_remote_media_guard_t022"),
                ("publishing_publicdeliveryasset", "pub_delivery_asset_guard_t022"),
                ("publishing_publicationmedia", "pub_media_binding_guard_t022"),
                ("publishing_publicationmedia", "pub_media_binding_insert_t022"),
                ("publishing_mediadeliveryoperation", "pub_media_operation_insert_t022"),
                ("publishing_mediadeliveryoperation", "pub_media_operation_guard_t022"),
            ):
                cursor.execute(f'DROP TRIGGER IF EXISTS "{name}" ON {table}')
            for name in POSTGRES_FUNCTION_NAMES:
                cursor.execute(f'DROP FUNCTION IF EXISTS "{name}"()')
            return
        raise RuntimeError(f"unsupported database vendor for T022 guards: {vendor}")


def reject_populated_reverse(apps, schema_editor):
    for model_name in (
        "PublicationMedia",
        "PublishedVisualizationInput",
        "PublishedVisualizationSnapshot",
        "PublishedEvidenceSnapshot",
        "PublishedAssetCohort",
        "MediaDeliveryOperation",
    ):
        model = apps.get_model("publishing", model_name)
        if model.objects.using(schema_editor.connection.alias).exists():
            raise IrreversibleError(
                "T022 published asset lineage must be empty before reverse migration"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_editorial_policy_runtime'),
        ('evidence', '0006_generic_evidence_manifest'),
        ('publishing', '0011_publication_attempt_fencing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedAssetCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schema_version', models.CharField(default='published-assets-v1', max_length=40)),
                ('material_state', models.CharField(choices=[('current', '현재 정본'), ('legacy_unverifiable', '레거시 검증 불가')], default='current', max_length=24)),
                ('item_count', models.PositiveIntegerField()),
                ('manifest', models.JSONField(default=list)),
                ('manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_asset_cohort', to='editorial.articlerevision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedEvidenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item_id', models.UUIDField()),
                ('source_version_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('source_url_snapshot', models.URLField(max_length=1000)),
                ('source_title_snapshot', models.CharField(max_length=1000)),
                ('source_publisher_snapshot', models.CharField(max_length=300)),
                ('source_published_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('source_modified_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('source_collected_at_snapshot', models.DateTimeField()),
                ('evidence_content_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('asset_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('object_key', models.CharField(max_length=1024)),
                ('object_version', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('locator_snapshot', models.JSONField(default=dict)),
                ('rights_status_snapshot', models.CharField(max_length=32)),
                ('rights_basis_url_snapshot', models.URLField(max_length=1000)),
                ('attribution_snapshot', models.TextField(blank=True)),
                ('alt_text_snapshot', models.TextField()),
                ('caption_snapshot', models.TextField()),
                ('presentation_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_snapshots', to='publishing.publishedassetcohort')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_asset_snapshots', to='evidence.evidenceasset')),
                ('visual_placement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_evidence_snapshot', to='editorial.visualplacement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedVisualizationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_checksum', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('object_key', models.CharField(max_length=1000)),
                ('object_version', models.CharField(max_length=500)),
                ('input_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('transform_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('renderer_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('mime_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('rights_status_snapshot', models.CharField(max_length=32)),
                ('rights_basis_url_snapshot', models.URLField(max_length=1000)),
                ('attribution_snapshot', models.TextField(blank=True)),
                ('alt_text_snapshot', models.TextField()),
                ('caption_snapshot', models.TextField()),
                ('presentation_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualization_snapshots', to='publishing.publishedassetcohort')),
                ('visual_placement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_visualization_snapshot', to='editorial.visualplacement')),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_snapshots', to='editorial.visualizationrender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedVisualizationInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.PositiveIntegerField()),
                ('input_material_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('evidence_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visualization_input_links', to='publishing.publishedevidencesnapshot')),
                ('visualization_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_links', to='publishing.publishedvisualizationsnapshot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('visualization_snapshot', 'display_order'), name='uq_published_visualization_input_order'), models.UniqueConstraint(fields=('visualization_snapshot', 'evidence_snapshot'), name='uq_published_visualization_input_evidence')],
            },
        ),
        migrations.RunPython(backfill_asset_cohorts, migrations.RunPython.noop),
        migrations.AddField(
            model_name='publicationmedia',
            name='asset_cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_media_bindings', to='publishing.publishedassetcohort'),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='evidence_snapshot_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publishing.publishedevidencesnapshot'),
        ),
        migrations.AddField(
            model_name='publicationmedia',
            name='visualization_snapshot_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='publishing.publishedvisualizationsnapshot'),
        ),
        migrations.RunPython(bind_existing_publication_media, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='publicationmedia',
            name='ck_publication_media_provenance_xor',
        ),
        migrations.RemoveField(
            model_name='publicationmedia',
            name='published_evidence_snapshot_id',
        ),
        migrations.RemoveField(
            model_name='publicationmedia',
            name='published_visualization_snapshot_id',
        ),
        migrations.RenameField(
            model_name='publicationmedia',
            old_name='evidence_snapshot_ref',
            new_name='published_evidence_snapshot',
        ),
        migrations.RenameField(
            model_name='publicationmedia',
            old_name='visualization_snapshot_ref',
            new_name='published_visualization_snapshot',
        ),
        migrations.AlterField(
            model_name='publicationmedia',
            name='published_evidence_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_media_bindings', to='publishing.publishedevidencesnapshot'),
        ),
        migrations.AlterField(
            model_name='publicationmedia',
            name='published_visualization_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_media_bindings', to='publishing.publishedvisualizationsnapshot'),
        ),
        migrations.AlterField(
            model_name='publicationmedia',
            name='asset_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publication_media_bindings', to='publishing.publishedassetcohort'),
        ),
        migrations.RemoveField(
            model_name='publicationmedia',
            name='evidence_asset_id',
        ),
        migrations.RemoveField(
            model_name='remotemedia',
            name='evidence_asset_id',
        ),
        migrations.RemoveField(
            model_name='publicdeliveryasset',
            name='source_evidence_asset_id',
        ),
        migrations.AlterField(
            model_name='remotemedia',
            name='asset_checksum',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')]),
        ),
        migrations.AlterField(
            model_name='remotemedia',
            name='presentation_hash',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')]),
        ),
        migrations.AlterField(
            model_name='publicdeliveryasset',
            name='asset_checksum',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')]),
        ),
        migrations.AlterField(
            model_name='publicdeliveryasset',
            name='presentation_hash',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')]),
        ),
        migrations.AlterField(
            model_name='publicdeliveryasset',
            name='delivery_object_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publicdeliveryasset',
            name='public_url',
            field=models.URLField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publicdeliveryasset',
            name='state',
            field=models.CharField(choices=[('pending', 'Preparing'), ('available', '사용 가능'), ('withdrawal_pending', '철회 대기'), ('pending_delete', '삭제 대기'), ('deleted', '삭제')], default='pending', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='publicationmedia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_evidence_snapshot__isnull', False), ('published_visualization_snapshot__isnull', True)), models.Q(('published_evidence_snapshot__isnull', True), ('published_visualization_snapshot__isnull', False)), _connector='OR'), name='ck_publication_media_provenance_xor'),
        ),
        migrations.AddConstraint(
            model_name='publicationmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('published_evidence_snapshot__isnull', False)), fields=('publication', 'published_evidence_snapshot'), name='uq_publication_evidence_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='publicationmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('published_visualization_snapshot__isnull', False)), fields=('publication', 'published_visualization_snapshot'), name='uq_publication_visual_snapshot'),
        ),
        migrations.CreateModel(
            name='MediaDeliveryOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_kind', models.CharField(choices=[('remote_media', 'WordPress media'), ('public_delivery_asset', 'Public delivery asset')], max_length=32)),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('prepare', 'Prepare'), ('reconcile', 'Reconcile'), ('delete', 'Delete')], max_length=16)),
                ('generation', models.PositiveIntegerField()),
                ('target_snapshot_id', models.UUIDField(blank=True, null=True)),
                ('target_config_hash', models.CharField(blank=True, max_length=64)),
                ('material_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a lowercase SHA-256 digest')])),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('unknown_outcome', 'Unknown outcome'), ('manual_required', 'Manual review required'), ('delivery_failed', 'Delivery failed'), ('superseded', 'Superseded')], default='queued', max_length=24)),
                ('consumer_name', models.CharField(blank=True, max_length=160)),
                ('consumer_lease_generation', models.PositiveBigIntegerField(default=0)),
                ('consumer_lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_token_hash', models.CharField(blank=True, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('write_marker', models.CharField(blank=True, max_length=64)),
                ('external_write_started_at', models.DateTimeField(blank=True, null=True)),
                ('result_hash', models.CharField(blank=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_delivery_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to='publishing.publicdeliveryasset')),
                ('publication_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_delivery_operations', to='publishing.publicationattempt')),
                ('publication_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_delivery_operations', to='publishing.publicationintent')),
                ('remote_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_operations', to='publishing.remotemedia')),
                ('source_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='media_delivery_operation', to='infrastructure.outboxmessage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('mapping_kind', 'remote_media'), ('public_delivery_asset__isnull', True), ('remote_media__isnull', False)), models.Q(('mapping_kind', 'public_delivery_asset'), ('public_delivery_asset__isnull', False), ('remote_media__isnull', True)), _connector='OR'), name='ck_media_operation_mapping_xor'), models.CheckConstraint(condition=models.Q(models.Q(('publication_attempt__isnull', True), ('publication_intent__isnull', True)), models.Q(('publication_attempt__isnull', False), ('publication_intent__isnull', False)), _connector='OR'), name='ck_media_operation_publication_pair'), models.CheckConstraint(condition=models.Q(('generation__gte', 1), ('generation__lte', 5)), name='ck_media_operation_generation_1_5'), models.UniqueConstraint(condition=models.Q(('remote_media__isnull', False)), fields=('remote_media', 'generation'), name='uq_remote_media_operation_generation'), models.UniqueConstraint(condition=models.Q(('public_delivery_asset__isnull', False)), fields=('public_delivery_asset', 'generation'), name='uq_delivery_asset_operation_generation'), models.UniqueConstraint(condition=models.Q(('remote_media__isnull', False), ('state__in', ('queued', 'running'))), fields=('remote_media',), name='uq_active_remote_media_operation'), models.UniqueConstraint(condition=models.Q(('public_delivery_asset__isnull', False), ('state__in', ('queued', 'running'))), fields=('public_delivery_asset',), name='uq_active_delivery_asset_operation')],
            },
        ),
        migrations.RunPython(install_asset_guards, remove_asset_guards),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=reject_populated_reverse,
        ),
    ]
