# Generated by Django 5.2.16 on 2026-07-17 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_code', models.CharField(choices=[('housing_subscription', '대한민국 부동산 청약정보'), ('semiconductor_news', '한국·글로벌 반도체 뉴스')], db_index=True, max_length=40)),
                ('key', models.SlugField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('base_url', models.URLField(max_length=500)),
                ('authority_tier', models.CharField(choices=[('primary_official', '공식 1차 출처'), ('primary_corporate', '기업 1차 출처'), ('trusted_secondary', '신뢰 보조 출처'), ('discovery_only', '발견 전용')], max_length=32)),
                ('access_method', models.CharField(choices=[('public_api', '공개 API'), ('open_data_api', '공공데이터 API'), ('rss_atom', 'RSS/Atom'), ('public_html', '공개 HTML'), ('public_file', '공개 파일')], max_length=32)),
                ('independence_group', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('current_snapshot_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['topic_code', 'display_name'],
                'constraints': [models.UniqueConstraint(fields=('topic_code', 'key'), name='uq_source_topic_key')],
            },
        ),
        migrations.CreateModel(
            name='SourceDefinitionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', '초안'), ('approved', '승인'), ('retired', '폐기')], default='draft', max_length=16)),
                ('config', models.JSONField(default=dict)),
                ('config_hash', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='topics.sourcedefinition')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRegistrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic_code', models.CharField(choices=[('housing_subscription', '대한민국 부동산 청약정보'), ('semiconductor_news', '한국·글로벌 반도체 뉴스')], max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', '초안'), ('approved', '승인'), ('retired', '폐기')], default='draft', max_length=16)),
                ('manifest_hash', models.CharField(max_length=64)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='SourceRegistryMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.sourcedefinitionsnapshot')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='topics.sourceregistrysnapshot')),
            ],
            options={
                'ordering': ['display_order', 'source_snapshot_id'],
            },
        ),
        migrations.CreateModel(
            name='TopicPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('housing_subscription', '대한민국 부동산 청약정보'), ('semiconductor_news', '한국·글로벌 반도체 뉴스')], max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('freshness_minutes', models.PositiveIntegerField(default=1440)),
                ('policy', models.JSONField(default=dict)),
                ('policy_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', '-version'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='uq_topic_policy_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcedefinitionsnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'version'), name='uq_source_snapshot_version'),
        ),
        migrations.AddConstraint(
            model_name='sourcedefinitionsnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'config_hash'), name='uq_source_snapshot_material'),
        ),
        migrations.AddConstraint(
            model_name='sourceregistrysnapshot',
            constraint=models.UniqueConstraint(fields=('topic_code', 'version'), name='uq_registry_topic_version'),
        ),
        migrations.AddConstraint(
            model_name='sourceregistrymembership',
            constraint=models.UniqueConstraint(fields=('registry', 'source_snapshot'), name='uq_registry_source_snapshot'),
        ),
    ]
